
### 获取所有用户
POST {{baseUrl}}/api/users/getAllUser
Content-Type: application/json
Authorization: Bearer {{token}}

{}


### 注册新用户
POST {{baseUrl}}/api/account/register
Content-Type: application/json

{
  "email": "arch3@test.com",
  "password": "a12345678",
  "confirmPassword": "a12345678"
}


### 登录
POST {{baseUrl}}/api/account/login
Content-Type: application/json

{
  "email": "arch3@test.com",
  "password": "a12345678"
}

### 刷新token
POST {{baseUrl}}/api/account/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}
