
### 注册新用户
POST {{baseUrl}}/api/v1/account/register
Content-Type: application/json

{
  "email": "arch3@test.com",
  "password": "a12345678",
  "confirmPassword": "a12345678"
}


### 登录
POST {{baseUrl}}/api/v1/account/login
Content-Type: application/json

{
  "email": "arch3@test.com",
  "password": "a12345678"
}

### 刷新 token
POST {{baseUrl}}/api/v1/account/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### 获取用户列表（分页，第 1 页，每页 20 条）
POST {{baseUrl}}/api/v1/users/list
Authorization: Bearer {{token}}

{
  "pageSize": "20",
  "page": "1"
}

### 获取用户列表（第 2 页）
POST {{baseUrl}}/api/v1/users/list
Authorization: Bearer {{token}}

{
  "pageSize": "20",
  "page": "1"
}


### 更新用户（id 从路径参数传入）
POST {{baseUrl}}/api/v1/users/update
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "updated@test.com",
  "id": "1"
}

### 删除用户（id 从路径参数传入）
POST {{baseUrl}}/api/v1/users/delete
Authorization: Bearer {{token}}


{
  "id": "1"
}