version: "3.9"

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CADDY_INGRESS_NETWORKS=app-network
    networks:
      - app-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - caddy_data:/data
    restart: unless-stopped

  api:
    build: ./backend
    container_name: api-service
    networks:
      - app-network
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydb
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=super_secret_123
    labels:
      caddy: api.find345.site
      # 这里直接写 3000，不要带服务名，caddy-docker-proxy 会自动处理
      caddy.reverse_proxy: "api:3000"
    restart: always

  db:
    image: postgres:16-alpine
    container_name: postgres-db
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    restart: always

  redis:
    image: redis:alpine
    container_name: redis-cache
    networks:
      - app-network
    # 除非你要从本地电脑连 Redis，否则不需要 ports
    volumes:
      - redis_data:/data
    restart: always

networks:
  app-network:
    name: app-network # 显式命名

volumes:
  caddy_data:
  postgres_data:
  redis_data: