services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CADDY_INGRESS_NETWORKS=app-network
    networks:
      - app-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

  api:
    build: ./backend
    networks:
      - app-network
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydb
      # 这里的 redis 是下方服务的名称
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=super_secret_123
    depends_on:
      - redis
    labels:
      caddy: api.find345.site
      caddy.reverse_proxy: "{{upstreams 3000}}"
    restart: always
    # 生产环境运行编译后的代码或直接运行入口，不带 --hot
#    command: bun run src/index.ts

  db:
    image: postgres:16-alpine
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    restart: always

  redis:
    image: redis:alpine
    networks:
      # 必须加入同一个网络
      - app-network
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

networks:
  app-network:
    external: false
    driver: bridge # 明确声明使用 bridge 模式

volumes:
  caddy_data:
  postgres_data:
  redis_data: