services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:latest
    container_name: caddy-gateway
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CADDY_INGRESS_NETWORKS=app-network
    networks:
      - app-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - caddy_data:/data
    restart: unless-stopped

  api-blue:
    build: .
    container_name: api-blue-service
    networks:
      - app-network
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydb
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=super_secret_123
    labels:
      caddy: api.find345.site
      caddy.reverse_proxy: "{{upstreams 3000}}"
    healthcheck:
      test: ["CMD", "bun", "-e", "fetch('http://127.0.0.1:3000/').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 10s
      timeout: 3s
      retries: 12
      start_period: 20s
    restart: always
    depends_on:
      - redis
      - db

  api-green:
    build: .
    container_name: api-green-service
    networks:
      - app-network
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydb
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=super_secret_123
    labels:
      caddy: api.find345.site
      caddy.reverse_proxy: "{{upstreams 3000}}"
    healthcheck:
      test: ["CMD", "bun", "-e", "fetch('http://127.0.0.1:3000/').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 10s
      timeout: 3s
      retries: 12
      start_period: 20s
    restart: always
    depends_on:
      - redis
      - db

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"  # 宿主机端口:容器端口
    container_name: postgres-db
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    restart: always

  redis:
    image: redis:alpine
    container_name: redis-cache
    networks:
      - app-network
    volumes:
      - redis_data:/data
    restart: always

networks:
  app-network:
    name: app-network

volumes:
  caddy_data:
  postgres_data:
  redis_data:
