apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ho-stack.fullname" . }}-secrets
  labels:
    {{- include "ho-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  POSTGRES_REPLICATION_USER: {{ .Values.postgres.replicationUser | quote }}
  POSTGRES_REPLICATION_PASSWORD: {{ .Values.postgres.replicationPassword | quote }}
  JWT_SECRET: {{ .Values.api.env.JWT_SECRET | quote }}
  DATABASE_WRITE_URL: {{ printf "postgres://%s:%s@%s:%v/%s" .Values.postgres.username .Values.postgres.password (include "ho-stack.pgbouncerRw" .) .Values.pgbouncer.port .Values.postgres.database | quote }}
  DATABASE_READ_URL: {{ printf "postgres://%s:%s@%s:%v/%s" .Values.postgres.username .Values.postgres.password (include "ho-stack.pgbouncerRo" .) .Values.pgbouncer.port .Values.postgres.database | quote }}
  REDIS_URL: {{ printf "redis://%s:%v" (include "ho-stack.redis" .) .Values.redis.port | quote }}
