# order-service/service.yaml — 订单与支付服务 ClusterIP Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecom.fullname" . }}-order-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ecom.labels" . | nindent 4 }}
    app.kubernetes.io/name: order-service
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.orderService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: order-service
    app.kubernetes.io/instance: {{ .Release.Name }}
