services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecom
    ports:
      - "5432:5432"
    volumes:
      - pg_dev_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  order-service:
    build: ../../services/order-service
    environment:
      DATABASE_URL: postgres://user:password@db:5432/ecom
      USER_SERVICE_URL: http://user-service:3001
    depends_on:
      - db
      - redis
      - user-service

  user-service:
    build: ../../services/user-service
    ports:
      - "3001:3000"

  inventory-service:
    build: ../../services/inventory-service
    ports:
      - "3002:3000"

  api-gateway:
    build: ../../apps/api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - order-service
      - user-service
      - inventory-service

volumes:
  pg_dev_data: