
### 获取所有用户
POST {{abc}}/api/users/getAllUser
Content-Type: application/json

{}


### 注册新用户
POST {{baseUrl}}/api/users/register
Content-Type: application/json

{
  "name": "架构师测试",
  "email": "arch2@test.com"
}