# product-service/service.yaml — 商品与库存服务 ClusterIP Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecom.fullname" . }}-product-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ecom.labels" . | nindent 4 }}
    app.kubernetes.io/name: product-service
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.productService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: product-service
    app.kubernetes.io/instance: {{ .Release.Name }}
