/**
 * 批量商品目录 — 补充各分类至 20+ 商品
 * 紧凑格式：每商品一行，由 seed-prod.ts 调用 bulkInsert 展开
 */

export interface BulkProduct {
  t: string;   // title
  s: string;   // slug
  b: string;   // brand
  d: string;   // description
  p: number;   // minPrice
  mp?: number; // maxPrice (defaults to p)
}

export interface CategoryBulk {
  catSlug: string;
  bg: string; // placeholder img background color
  products: BulkProduct[];
}

export const bulkCatalog: CategoryBulk[] = [
  // ── 手机 (16 more → 20 total) ──
  { catSlug: 'phones', bg: '3B82F6', products: [
    { t: 'OPPO Find X7 Ultra', s: 'oppo-find-x7-ultra', b: 'OPPO', d: '哈苏影像系统，双潜望长焦，骁龙8 Gen3', p: 5999, mp: 6999 },
    { t: 'vivo X100 Pro+', s: 'vivo-x100-pro-plus', b: 'vivo', d: '蔡司影像，天玑9300+，全焦段人像', p: 5499, mp: 6499 },
    { t: '一加 12', s: 'oneplus-12', b: 'OnePlus', d: '骁龙8 Gen3，哈苏影像，100W闪充', p: 4299, mp: 5299 },
    { t: '荣耀 Magic6 Pro', s: 'honor-magic6-pro', b: '荣耀', d: '骁龙8 Gen3，鹰眼相机，青海湖电池', p: 4999, mp: 5999 },
    { t: 'realme GT5 Pro', s: 'realme-gt5-pro', b: 'realme', d: '骁龙8 Gen3，索尼LYT-808主摄，5400mAh', p: 2799, mp: 3499 },
    { t: 'iQOO 12 Pro', s: 'iqoo-12-pro', b: 'iQOO', d: '骁龙8 Gen3，自研芯片Q1，电竞旗舰', p: 4499, mp: 5499 },
    { t: '红米 K70 Pro', s: 'redmi-k70-pro', b: '红米', d: '骁龙8 Gen3，2K华星屏，120W快充', p: 2999, mp: 3599 },
    { t: 'iPhone 15', s: 'iphone-15', b: 'Apple', d: 'A16芯片，灵动岛，4800万主摄', p: 5999, mp: 7599 },
    { t: 'Samsung Galaxy Z Fold5', s: 'samsung-galaxy-z-fold5', b: 'Samsung', d: '折叠屏旗舰，7.6英寸大屏，Flex模式', p: 12999, mp: 14999 },
    { t: 'Samsung Galaxy Z Flip5', s: 'samsung-galaxy-z-flip5', b: 'Samsung', d: '小折叠，3.4英寸外屏，轻巧时尚', p: 6999, mp: 7999 },
    { t: '索尼 Xperia 1 V', s: 'sony-xperia-1-v', b: 'Sony', d: '4K OLED屏，Alpha相机技术，Hi-Res音频', p: 7999, mp: 8999 },
    { t: 'Google Pixel 8 Pro', s: 'google-pixel-8-pro', b: 'Google', d: 'Tensor G3芯片，AI摄影，原生安卓体验', p: 6999, mp: 8499 },
    { t: '努比亚 Z60 Ultra', s: 'nubia-z60-ultra', b: '努比亚', d: '骁龙8 Gen3，全面屏无打孔，6000mAh', p: 4499, mp: 5499 },
    { t: '魅族 21 Pro', s: 'meizu-21-pro', b: '魅族', d: '骁龙8 Gen3，Flyme系统，无界设计', p: 4299, mp: 5299 },
    { t: 'Nothing Phone 2', s: 'nothing-phone-2', b: 'Nothing', d: 'Glyph灯带，骁龙8+，透明后盖设计', p: 3299, mp: 3999 },
    { t: 'iPhone SE 第四代', s: 'iphone-se-4', b: 'Apple', d: 'A15芯片，OLED全面屏，高性价比iPhone', p: 3499, mp: 4199 },
  ]},

  // ── 耳机 (17 more → 20 total) ──
  { catSlug: 'earphones', bg: '6366F1', products: [
    { t: 'Bose QuietComfort Ultra 耳塞', s: 'bose-qc-ultra-earbuds', b: 'Bose', d: '沉浸式空间音频，CustomTune智能调音', p: 1899 },
    { t: 'JBL Tour One M2 头戴降噪', s: 'jbl-tour-one-m2', b: 'JBL', d: '真自适应降噪，Hi-Res认证，50小时续航', p: 1999 },
    { t: '漫步者 TWS NB3 Pro', s: 'edifier-tws-nb3-pro', b: '漫步者', d: '-49dB深度降噪，LDAC高清编解码', p: 499, mp: 599 },
    { t: '小米 Buds 4 Pro', s: 'xiaomi-buds-4-pro', b: '小米', d: '48dB智能降噪，LDAC+LHDC双高清', p: 999 },
    { t: '森海塞尔 Momentum 4', s: 'sennheiser-momentum-4', b: '森海塞尔', d: '60小时续航，自适应降噪，42mm驱动', p: 2499 },
    { t: '铁三角 ATH-M50x 专业监听', s: 'audio-technica-ath-m50x', b: '铁三角', d: '45mm大驱动单元，专业录音室监听级', p: 899 },
    { t: 'Beats Studio Pro', s: 'beats-studio-pro', b: 'Beats', d: '个性化空间音频，USB-C，40小时续航', p: 2499 },
    { t: 'JBL Tune 770NC', s: 'jbl-tune-770nc', b: 'JBL', d: '自适应降噪，JBL Pure Bass音效', p: 599 },
    { t: '万魔 1MORE EVO', s: '1more-evo', b: '万魔', d: '圈铁双单元，LDAC高清，42dB降噪', p: 799 },
    { t: 'FIIL CC Pro 2', s: 'fiil-cc-pro-2', b: 'FIIL', d: '42dB降噪，双设备连接，ENC通话降噪', p: 399 },
    { t: '飞利浦 Fidelio L4', s: 'philips-fidelio-l4', b: '飞利浦', d: '40mm驱动单元，ANC Pro+，50小时续航', p: 1699 },
    { t: 'Jabra Elite 10', s: 'jabra-elite-10', b: 'Jabra', d: 'Dolby Atmos头部追踪，舒适贴合设计', p: 1699 },
    { t: 'Samsung Galaxy Buds FE', s: 'samsung-galaxy-buds-fe', b: 'Samsung', d: 'AKG调校，主动降噪，IPX2防水', p: 499 },
    { t: 'OPPO Enco X2', s: 'oppo-enco-x2', b: 'OPPO', d: '丹拿联合调音，LHDC 5.0高清编码', p: 999 },
    { t: '荣耀 Earbuds X5', s: 'honor-earbuds-x5', b: '荣耀', d: '27小时续航，通话降噪，10mm动圈', p: 199 },
    { t: 'B&O Beoplay EX', s: 'bo-beoplay-ex', b: 'B&O', d: '丹麦工艺，自适应ANC，无线充电', p: 2698 },
    { t: '漫步者 W820NB Plus', s: 'edifier-w820nb-plus', b: '漫步者', d: '-38dB降噪，49小时续航，游戏低延迟', p: 299 },
  ]},

  // ── 智能手表 (17 more → 20 total) ──
  { catSlug: 'smart-watches', bg: '8B5CF6', products: [
    { t: '小米 Watch S3', s: 'xiaomi-watch-s3', b: '小米', d: 'AMOLED大屏，eSIM独立通话，15天续航', p: 999, mp: 1199 },
    { t: '华为 Watch 4 Pro', s: 'huawei-watch-4-pro', b: '华为', d: '鸿蒙系统，eSIM独立通话，健康监测', p: 3399, mp: 3999 },
    { t: 'OPPO Watch 4 Pro', s: 'oppo-watch-4-pro', b: 'OPPO', d: '双芯架构，LTPO AMOLED，独立eSIM', p: 2299, mp: 2699 },
    { t: 'Garmin Venu 3', s: 'garmin-venu-3', b: 'Garmin', d: 'AMOLED屏，轮椅模式，睡眠教练', p: 3280 },
    { t: 'Garmin Forerunner 265', s: 'garmin-forerunner-265', b: 'Garmin', d: '跑步动态，训练就绪度，AMOLED彩屏', p: 3080 },
    { t: 'Amazfit GTR 4', s: 'amazfit-gtr-4', b: 'Amazfit', d: '双频GPS，150+运动模式，14天续航', p: 999 },
    { t: 'TicWatch Pro 5', s: 'ticwatch-pro-5', b: 'TicWatch', d: '骁龙W5+ Gen 1，双屏显示，WearOS', p: 2199 },
    { t: 'Apple Watch Series 9', s: 'apple-watch-series-9', b: 'Apple', d: 'S9芯片，双指互点，亮度2000尼特', p: 2999, mp: 4299 },
    { t: 'Apple Watch SE 第二代', s: 'apple-watch-se-2', b: 'Apple', d: '核心健康功能，运动检测，家人共享', p: 1999, mp: 2399 },
    { t: '小米手环 8 Pro', s: 'xiaomi-band-8-pro', b: '小米', d: '1.74英寸AMOLED，独立GPS，150+运动', p: 299 },
    { t: 'HUAWEI Band 9', s: 'huawei-band-9', b: '华为', d: '1.47英寸AMOLED，舒适佩戴，14天续航', p: 249 },
    { t: 'Fitbit Charge 6', s: 'fitbit-charge-6', b: 'Fitbit', d: 'Google地图导航，YouTube Music，7天续航', p: 1098 },
    { t: 'Coros Pace 3', s: 'coros-pace-3', b: 'Coros', d: '双频GPS，24天续航，跑步功率', p: 1499 },
    { t: 'Polar Pacer Pro', s: 'polar-pacer-pro', b: 'Polar', d: '跑步功率计，恢复建议，GPS多卫星', p: 1999 },
    { t: '颂拓 Suunto 9 Peak Pro', s: 'suunto-9-peak-pro', b: 'Suunto', d: '钛合金表圈，双频GPS，300米防水', p: 3980 },
    { t: '佳明 Instinct 2X Solar', s: 'garmin-instinct-2x-solar', b: 'Garmin', d: '太阳能充电，军标耐用，LED手电筒', p: 2780 },
    { t: '小天才 Z9 儿童手表', s: 'xtc-z9-kids-watch', b: '小天才', d: '翻转双摄，九重定位，楼层定位', p: 1598 },
  ]},

  // ── 笔记本电脑 (17 more → 20 total) ──
  { catSlug: 'laptops', bg: '4F46E5', products: [
    { t: '戴尔 XPS 15 9530', s: 'dell-xps-15-9530', b: 'Dell', d: 'i7-13700H，15.6英寸3.5K OLED，轻薄高端', p: 11999, mp: 15999 },
    { t: 'HP Spectre x360 14', s: 'hp-spectre-x360-14', b: 'HP', d: '翻转触控，2.8K OLED，Intel Evo认证', p: 10999, mp: 13999 },
    { t: 'Surface Laptop 5', s: 'surface-laptop-5', b: 'Microsoft', d: 'i5/i7可选，触控屏，极致轻薄', p: 8888, mp: 12888 },
    { t: '华硕 灵耀14 2024', s: 'asus-zenbook-14-2024', b: 'ASUS', d: 'Intel Core Ultra，2.8K OLED，轻至1.2kg', p: 6999, mp: 8999 },
    { t: '小米 Book Pro 16 2024', s: 'xiaomi-book-pro-16-2024', b: '小米', d: 'i7-13700H，3.2K 120Hz屏，高性能轻薄本', p: 6499, mp: 7999 },
    { t: '联想 小新 Pro 16 2024', s: 'lenovo-xiaoxin-pro-16-2024', b: 'Lenovo', d: 'i7-13700H，2.5K 120Hz，高性价比全能本', p: 5499, mp: 6999 },
    { t: '惠普 暗影精灵9', s: 'hp-omen-9', b: 'HP', d: 'i7+RTX4060，16.1英寸144Hz电竞屏', p: 7999, mp: 9999 },
    { t: '戴尔 游匣 G16', s: 'dell-g16-gaming', b: 'Dell', d: 'i7+RTX4060，16英寸165Hz，大屏游戏本', p: 7499, mp: 9499 },
    { t: '机械革命 极光X', s: 'mechrevo-aurora-x', b: '机械革命', d: 'i9+RTX4070，2.5K 240Hz，性价比游戏本', p: 8999, mp: 10999 },
    { t: '雷蛇 Blade 15 2024', s: 'razer-blade-15-2024', b: 'Razer', d: 'i9+RTX4070，QHD 240Hz，CNC铝合金', p: 16999, mp: 22999 },
    { t: '宏碁 暗影骑士 擎 2024', s: 'acer-nitro-v-2024', b: 'Acer', d: 'i5+RTX4060，15.6英寸144Hz，学生游戏本', p: 5999, mp: 7499 },
    { t: 'Framework Laptop 16', s: 'framework-laptop-16', b: 'Framework', d: '模块化设计，可自行升级维修，RX7700S', p: 11999, mp: 15999 },
    { t: 'MacBook Air 15 M3', s: 'macbook-air-15-m3', b: 'Apple', d: 'M3芯片，15.3英寸，18小时续航，无风扇', p: 10499, mp: 14499 },
    { t: '华为 MateBook X Pro 2024', s: 'huawei-matebook-x-pro-2024', b: '华为', d: 'OLED原色屏，超级终端，轻至980g', p: 11999, mp: 14999 },
    { t: '荣耀 MagicBook 14 2024', s: 'honor-magicbook-14-2024', b: '荣耀', d: 'Intel Ultra 7，2.8K OLED，OS Turbo', p: 5999, mp: 7499 },
    { t: '微星 绝影16 HX', s: 'msi-stealth-16-hx', b: 'MSI', d: 'i9-13950HX+RTX4080，Mini LED屏', p: 17999, mp: 21999 },
    { t: '华硕 ROG Flow Z13', s: 'asus-rog-flow-z13', b: 'ASUS', d: '13.4英寸平板+键盘，i9+RTX4060，二合一', p: 12999, mp: 15999 },
  ]},

  // ── 平板电脑 (17 more → 20 total) ──
  { catSlug: 'tablets', bg: '7C3AED', products: [
    { t: 'iPad Pro 12.9 M2', s: 'ipad-pro-12-m2', b: 'Apple', d: 'M2芯片，12.9英寸Liquid Retina XDR，ProMotion', p: 8999, mp: 16999 },
    { t: 'iPad mini 第六代', s: 'ipad-mini-6', b: 'Apple', d: 'A15芯片，8.3英寸，便携小屏旗舰', p: 3799, mp: 5199 },
    { t: '小米 Pad 6 Pro', s: 'xiaomi-pad-6-pro', b: '小米', d: '骁龙8+，11英寸2.8K 144Hz，67W快充', p: 2399, mp: 2999 },
    { t: '联想 小新 Pad Pro 12.7', s: 'lenovo-xiaoxin-pad-pro-12', b: 'Lenovo', d: '骁龙870，12.7英寸2K，JBL四扬声器', p: 1999, mp: 2499 },
    { t: '华为 MatePad 11.5 S', s: 'huawei-matepad-11-5s', b: '华为', d: '骁龙7 Gen 1，2.2K 144Hz，手写笔支持', p: 2299, mp: 2799 },
    { t: 'Samsung Galaxy Tab A9+', s: 'samsung-galaxy-tab-a9-plus', b: 'Samsung', d: '11英寸LCD，四扬声器，轻量入门平板', p: 1499, mp: 1999 },
    { t: 'OPPO Pad 2', s: 'oppo-pad-2', b: 'OPPO', d: '天玑9000，11.61英寸2.8K，9510mAh', p: 2299, mp: 2999 },
    { t: '荣耀平板 V8 Pro', s: 'honor-tablet-v8-pro', b: '荣耀', d: '天玑8100，12.1英寸2.5K 144Hz', p: 2699, mp: 3399 },
    { t: 'vivo Pad2', s: 'vivo-pad2', b: 'vivo', d: '天玑9000，12.1英寸2.8K 144Hz，原OS', p: 2499, mp: 2999 },
    { t: 'Redmi Pad SE', s: 'redmi-pad-se', b: '红米', d: '骁龙680，11英寸FHD+，8000mAh大电池', p: 999, mp: 1299 },
    { t: '酷比魔方 iPlay 50 Pro', s: 'alldocube-iplay-50-pro', b: '酷比魔方', d: '天玑1080，10.4英寸2K，8GB+128GB', p: 899, mp: 1099 },
    { t: '联想 拯救者 Y700 2023', s: 'lenovo-legion-y700-2023', b: 'Lenovo', d: '骁龙8+，8.8英寸2.5K 144Hz，游戏平板', p: 2499, mp: 2999 },
    { t: 'Surface Pro 9', s: 'surface-pro-9', b: 'Microsoft', d: 'i5/i7可选，13英寸触屏，二合一生产力', p: 8888, mp: 15888 },
    { t: 'Amazon Fire Max 11', s: 'amazon-fire-max-11', b: 'Amazon', d: '11英寸2K，八核处理器，Alexa语音助手', p: 1299 },
    { t: 'realme Pad 2', s: 'realme-pad-2', b: 'realme', d: '联发科 Helio G99，11.5英寸2K，轻薄入门', p: 1199, mp: 1599 },
    { t: '努比亚 nubia Pad 3D II', s: 'nubia-pad-3d-2', b: '努比亚', d: '裸眼3D平板，12.4英寸2.5K，骁龙888', p: 3999 },
    { t: '台电 T60 平板', s: 'teclast-t60', b: '台电', d: '紫光展锐T606，12英寸，2K大屏，入门款', p: 699, mp: 899 },
  ]},

  // ── 键盘鼠标 (17 more → 20 total) ──
  { catSlug: 'keyboards', bg: '374151', products: [
    { t: '罗技 MX Mechanical 无线机械', s: 'logitech-mx-mechanical', b: 'Logitech', d: '智能背光，矮轴手感，三设备切换', p: 999 },
    { t: 'Cherry MX 3.0S 机械键盘', s: 'cherry-mx-3-0s', b: 'Cherry', d: '德国原厂Cherry轴体，铝合金框架', p: 599, mp: 799 },
    { t: '达尔优 A87 Pro 三模机械', s: 'dareu-a87-pro', b: '达尔优', d: 'Gasket结构，PBT键帽，三模热插拔', p: 329, mp: 399 },
    { t: '杜伽 K620W 三模机械', s: 'durgod-k620w', b: '杜伽', d: '65%紧凑布局，PBT二色键帽，铝壳', p: 499 },
    { t: '利奥博德 FC660C', s: 'leopold-fc660c', b: 'Leopold', d: '静电容轴体，PBT键帽，极简设计', p: 1399 },
    { t: '阿米洛 VA87M 机械键盘', s: 'varmilo-va87m', b: 'Varmilo', d: 'Cherry轴可选，主题定制，PBT五面热升华', p: 599, mp: 799 },
    { t: 'NuPhy Air75 V2', s: 'nuphy-air75-v2', b: 'NuPhy', d: '超薄矮轴，75%布局，RGB背光', p: 599 },
    { t: '腹灵 MK870', s: 'fl-mk870', b: '腹灵', d: '侧刻80%布局，Gasket结构，三模热插拔', p: 299, mp: 399 },
    { t: '罗技 K580 无线键盘', s: 'logitech-k580', b: 'Logitech', d: '超薄静音，双设备切换，24个月续航', p: 229 },
    { t: '微软 人体工学键盘', s: 'microsoft-ergonomic-keyboard', b: 'Microsoft', d: '分体式设计，柔软掌托，自然打字角度', p: 699 },
    { t: '雷蛇 猎魂光蛛V3 Pro', s: 'razer-huntsman-v3-pro', b: 'Razer', d: '模拟光轴，快速触发，磁力轴体', p: 1699 },
    { t: 'Corsair K65 Plus', s: 'corsair-k65-plus', b: 'Corsair', d: '75%布局，预润红轴，RGB，8000Hz轮询', p: 899 },
    { t: 'SteelSeries Apex Pro TKL', s: 'steelseries-apex-pro-tkl', b: 'SteelSeries', d: '可调触发行程0.1mm，OmniPoint磁力轴', p: 1399 },
    { t: 'HyperX Alloy Origins 65', s: 'hyperx-alloy-origins-65', b: 'HyperX', d: '铝合金框架，65%布局，HyperX红轴', p: 599 },
    { t: '雷柏 V500 Pro', s: 'rapoo-v500-pro', b: '雷柏', d: '87键三模，PBT键帽，高性价比入门', p: 149 },
    { t: '黑峡谷 M1 无线机械', s: 'hexgears-m1', b: '黑峡谷', d: '75%布局，Kailh矮轴，Mac/Win双系统', p: 499 },
    { t: '狼蛛 F87 客制化机械', s: 'aula-f87', b: '狼蛛', d: 'Gasket结构，80%热插拔，冰晶轴体', p: 199 },
  ]},

  // ── 冰箱洗衣机 (17 more → 20 total) ──
  { catSlug: 'big-appliance', bg: '0EA5E9', products: [
    { t: '美的 滚筒洗衣机 MG100V70WD5', s: 'midea-washer-mg100v', b: '美的', d: '10kg变频滚筒，BLDC变频，15分钟快洗', p: 2299 },
    { t: '海尔 波轮洗衣机 EB80M39TH', s: 'haier-washer-eb80m', b: '海尔', d: '8kg大容量波轮，智能称重，桶自洁', p: 1099 },
    { t: '松下 冰箱 NR-EW61WG', s: 'panasonic-fridge-ew61wg', b: '松下', d: '618L法式多门冰箱，-3℃微冻保鲜', p: 5999, mp: 6999 },
    { t: '美的 对开门冰箱 BCD-606WKPZM', s: 'midea-fridge-606', b: '美的', d: '606L对开门，一级能效变频，净味杀菌', p: 3499 },
    { t: '格力 空调 KFR-72LW 3匹柜机', s: 'gree-ac-kfr72lw', b: '格力', d: '3匹柜机，新一级能效，WiFi智控', p: 6999 },
    { t: '海信 75英寸 ULED 电视', s: 'hisense-75-uled-tv', b: '海信', d: '75英寸4K，ULED X 背光，120Hz高刷', p: 5999 },
    { t: 'TCL 65英寸 Mini LED 电视', s: 'tcl-65-miniled-tv', b: 'TCL', d: '65英寸Mini LED，量子点，144Hz VRR', p: 4999 },
    { t: '小米电视 S75 Mini LED', s: 'xiaomi-tv-s75-miniled', b: '小米', d: '75英寸Mini LED，1000nit峰值亮度', p: 4499 },
    { t: '创维 65英寸 OLED 电视', s: 'skyworth-65-oled-tv', b: '创维', d: '65英寸4K OLED，JBL音响，变色龙画质', p: 7999 },
    { t: '海尔 电热水器 EC6003-JT3', s: 'haier-water-heater-60l', b: '海尔', d: '60L电热水器，3000W速热，一级能效', p: 1599 },
    { t: '美的 燃气热水器 JSQ30-RX7', s: 'midea-gas-heater-rx7', b: '美的', d: '16L零冷水燃气热水器，恒温舒适', p: 2499 },
    { t: '方太 油烟机 EMD6T', s: 'fotile-range-hood-emd6t', b: '方太', d: '蝶翼环吸，23m³/min大风量，自动巡航', p: 4999 },
    { t: '老板 燃气灶 9B52', s: 'robam-gas-stove-9b52', b: '老板', d: '5.2kW大火力，一级能效，防干烧保护', p: 2199 },
    { t: '博世 洗碗机 SJV4HKX00C', s: 'bosch-dishwasher-sjv4h', b: '博世', d: '13套嵌入式洗碗机，6种程序，静音42dB', p: 5999 },
    { t: '小天鹅 烘干机 TH100VTG57WIT', s: 'littleswan-dryer-th100', b: '小天鹅', d: '10kg热泵烘干，紫外除菌，低温柔烘', p: 3999 },
    { t: '格力 除湿机 DH40EH', s: 'gree-dehumidifier-dh40', b: '格力', d: '40L/天除湿量，干衣模式，水满停机', p: 1899 },
    { t: '大金 中央空调 一拖四', s: 'daikin-central-ac-4', b: '大金', d: '一拖四家用中央空调，全直流变频，静音', p: 29999, mp: 35999 },
  ]},

  // ── 小家电 (17 more → 20 total) ──
  { catSlug: 'small-appliance', bg: '4B5563', products: [
    { t: '小米 空气净化器 4 Pro', s: 'xiaomi-air-purifier-4-pro', b: '小米', d: '500m³/h CADR，OLED触控屏，米家联动', p: 1499 },
    { t: '飞利浦 剃须刀 S9986', s: 'philips-shaver-s9986', b: '飞利浦', d: 'SkinIQ智能感应，纳米刀片，IPX7防水', p: 1999 },
    { t: '博朗 电动牙刷 iO Series 9', s: 'oral-b-io-series-9', b: '博朗', d: '3D微磁电动，7种模式，AI追踪刷牙', p: 1999 },
    { t: '松下 纳米水离子吹风机 EH-NA9K', s: 'panasonic-nanoe-eh-na9k', b: '松下', d: '纳米水离子，矿物质负离子，速干护发', p: 899 },
    { t: '美的 智能加湿器 SC-3C40', s: 'midea-humidifier-sc3c40', b: '美的', d: '4L大容量，上加水，银离子抑菌，静音', p: 199 },
    { t: '科沃斯 T20 Pro 扫拖一体', s: 'ecovacs-t20-pro', b: '科沃斯', d: '热水洗拖布60℃，5500Pa大吸力，AI避障', p: 3999 },
    { t: '追觅 S10 Pro Ultra', s: 'dreame-s10-pro-ultra', b: '追觅', d: '全能基站自清洁，7000Pa吸力，智能建图', p: 4499 },
    { t: '德尔玛 蒸汽拖把 ZQ610', s: 'deerma-steam-mop-zq610', b: '德尔玛', d: '高温蒸汽除菌，一键喷射，5秒速热', p: 399 },
    { t: '小熊 落地式加湿器 5L', s: 'bear-humidifier-5l', b: '小熊', d: '5L大容量，上加水，恒湿智控，银离子', p: 259 },
    { t: '莱克 立式吸尘器 M12 Max', s: 'lake-vacuum-m12-max', b: '莱克', d: '180W大功率，魔洁M12，地毯深度清洁', p: 3299 },
    { t: '飞利浦 空气炸锅 HD9270', s: 'philips-air-fryer-hd9270', b: '飞利浦', d: '6.2L大容量，快速空气技术，7大预设', p: 599 },
    { t: '小米 净水器 1600G', s: 'xiaomi-water-purifier-1600g', b: '小米', d: '1600G大通量，RO反渗透，直饮即滤', p: 2499 },
    { t: '安克 充电器 67W GaN', s: 'anker-charger-67w-gan', b: 'Anker', d: '67W氮化镓，三口输出，折叠插脚', p: 199 },
    { t: '绿联 充电宝 20000mAh 65W', s: 'ugreen-powerbank-20000-65w', b: '绿联', d: '20000mAh，65W双向快充，可充笔记本', p: 299 },
    { t: 'Bose SoundLink Flex 蓝牙音箱', s: 'bose-soundlink-flex', b: 'Bose', d: 'IP67防水，PositionIQ技术，12小时续航', p: 999 },
    { t: 'JBL Charge 5 蓝牙音箱', s: 'jbl-charge-5', b: 'JBL', d: 'IP67防尘防水，20小时续航，可充电', p: 999 },
    { t: 'Marshall Stanmore II 蓝牙音箱', s: 'marshall-stanmore-2', b: 'Marshall', d: '经典摇滚外观，低音炮+高音炮，蓝牙5.0', p: 2499 },
  ]},

  // ── 厨房电器 (17 more → 20 total) ──
  { catSlug: 'kitchen-appliance', bg: 'F59E0B', products: [
    { t: '九阳 空气炸锅 KL55-VF711', s: 'joyoung-air-fryer-vf711', b: '九阳', d: '5.5L大容量，可视窗口，无需翻面', p: 299 },
    { t: '苏泊尔 电压力锅 SY-60YC8110', s: 'supor-pressure-cooker-60yc', b: '苏泊尔', d: '6L不粘内胆，一锅双胆，12h预约', p: 399, mp: 499 },
    { t: '美的 破壁机 MJ-PB80Easy', s: 'midea-blender-pb80', b: '美的', d: '800W大功率，8叶刀头，10大功能', p: 399 },
    { t: '小米 米家电磁炉 A1', s: 'xiaomi-induction-cooker-a1', b: '小米', d: '99档精准火力，NEG面板，定时功能', p: 199 },
    { t: '摩飞 多功能料理锅 MR9088', s: 'morphyrichards-cooker-mr9088', b: '摩飞', d: '一锅六用，蒸煮煎炸烤涮，不粘涂层', p: 599 },
    { t: '东菱 绞肉机 DL-JR371', s: 'donlim-meat-grinder-jr371', b: '东菱', d: '双档调速，2L大容量，四叶刀头', p: 89 },
    { t: '北鼎 养生壶 K2693', s: 'buydeem-health-pot-k2693', b: '北鼎', d: '复古英伦风，11大功能，加厚高硼硅玻璃', p: 699 },
    { t: '膳魔师 保温杯 JNL-503', s: 'thermos-jnl-503', b: '膳魔师', d: '500ml超轻，真空断热，6小时保温', p: 199, mp: 259 },
    { t: '小熊 酸奶机 SNJ-C10H1', s: 'bear-yogurt-maker-c10h1', b: '小熊', d: '1L大容量，陶瓷内胆，智能恒温', p: 99 },
    { t: '松下 面包机 SD-PT1001', s: 'panasonic-bread-maker-pt1001', b: '松下', d: '自动投料，22种菜单，变频揉面', p: 1999 },
    { t: '西门子 嵌入式烤箱 HB233ABS0W', s: 'siemens-oven-hb233', b: '西门子', d: '71L大容量，3D热风，5层烤架', p: 3999 },
    { t: '美的 微蒸烤一体机 PG2310', s: 'midea-steam-oven-pg2310', b: '美的', d: '23L微蒸烤三合一，变频微波，蒸汽嫩烤', p: 1999 },
    { t: '德龙 半自动咖啡机 EC9335', s: 'delonghi-ec9335', b: 'DeLonghi', d: '15Bar萃取，感应研磨，卡布奇诺系统', p: 3499 },
    { t: '苏泊尔 电饭煲 SF40HC735', s: 'supor-rice-cooker-sf40hc', b: '苏泊尔', d: '4L球釜IH，智能预约，远红外加热', p: 599 },
    { t: '方太 蒸烤一体机 ZK-E3', s: 'fotile-steam-oven-zke3', b: '方太', d: '嵌入式蒸烤，3合1多功能，110℃过温蒸', p: 7999 },
    { t: '格兰仕 微波炉 G80F23CSL-Q6', s: 'galanz-microwave-g80f23', b: '格兰仕', d: '23L平板加热，700W，六档火力', p: 499 },
    { t: '惠而浦 台式洗碗机 WFC3C22PX', s: 'whirlpool-dishwasher-wfc3c', b: '惠而浦', d: '14套大容量，8种程序，第三层碗篮', p: 3299 },
  ]},

  // ── 男装 (17 more → 20 total) ──
  { catSlug: 'menswear', bg: '1E40AF', products: [
    { t: '优衣库 男士牛津纺衬衫', s: 'uniqlo-oxford-shirt-men', b: 'UNIQLO', d: '长袖修身版，100%棉牛津纺，商务休闲', p: 149 },
    { t: '海澜之家 商务夹克', s: 'heilan-home-blazer', b: '海澜之家', d: '弹力面料，修身版型，春秋通勤款', p: 499, mp: 699 },
    { t: '杰克琼斯 连帽卫衣', s: 'jack-jones-hoodie', b: 'Jack&Jones', d: '纯棉毛圈，宽松版型，经典Logo印花', p: 299, mp: 399 },
    { t: 'Zara 男士修身西裤', s: 'zara-slim-trousers-men', b: 'Zara', d: '弹力混纺面料，九分修身，商务通勤', p: 399 },
    { t: 'H&M 基础款圆领T恤 3件装', s: 'hm-basic-tee-3pack-men', b: 'H&M', d: '纯棉圆领，黑白灰三件套，基础百搭', p: 129 },
    { t: 'GXG 男士中长风衣', s: 'gxg-trench-coat-men', b: 'GXG', d: '双排扣设计，挺阔面料，英伦风格', p: 899 },
    { t: '太平鸟男装 棒球外套', s: 'peacebird-baseball-jacket-men', b: '太平鸟', d: 'PU皮拼接，刺绣Logo，美式复古', p: 599 },
    { t: '马克华菲 牛仔夹克', s: 'fairwhale-denim-jacket', b: '马克华菲', d: '水洗做旧，经典翻领，纯棉牛仔', p: 499 },
    { t: 'Calvin Klein 男士平角内裤 3条装', s: 'ck-boxer-brief-3pack', b: 'Calvin Klein', d: '弹力棉质，经典腰带Logo，舒适贴合', p: 299 },
    { t: 'BOSS 男士商务Polo衫', s: 'boss-polo-shirt-men', b: 'BOSS', d: '丝光棉面料，修身版型，刺绣Logo', p: 999 },
    { t: '七匹狼 轻薄羽绒服 男款', s: 'septwolves-down-jacket-men', b: '七匹狼', d: '90%白鸭绒，立领短款，轻薄保暖', p: 699, mp: 899 },
    { t: '九牧王 商务休闲西裤', s: 'joeone-business-pants', b: '九牧王', d: '免烫面料，直筒修身，舒适弹力', p: 299, mp: 399 },
    { t: '利郎 免烫衬衫 男款', s: 'lilanz-wrinkle-free-shirt', b: '利郎', d: '全棉免烫，商务正装，竹纤维内衬', p: 259 },
    { t: '报喜鸟 西装套装 男款', s: 'saint-angelo-suit-set', b: '报喜鸟', d: '精纺毛料，修身两粒扣，含西裤', p: 1999, mp: 2999 },
    { t: 'FILA 男士运动外套 梭织', s: 'fila-woven-jacket-men', b: 'FILA', d: '梭织面料，连帽设计，运动休闲', p: 599, mp: 799 },
    { t: 'Columbia 男士抓绒衫', s: 'columbia-fleece-men', b: 'Columbia', d: 'Steens Mountain抓绒，全拉链，轻量保暖', p: 399 },
    { t: '始祖鸟 Gamma LT 软壳夹克', s: 'arcteryx-gamma-lt-jacket', b: "Arc'teryx", d: 'Fortius Air面料，防风透气，四向弹力', p: 2800 },
  ]},

  // ── 女装 (17 more → 20 total) ──
  { catSlug: 'womenswear', bg: 'EC4899', products: [
    { t: 'ZARA 针织开衫 女款', s: 'zara-knit-cardigan-women', b: 'Zara', d: 'V领短款，珍珠扣装饰，柔软混纺', p: 299 },
    { t: 'H&M 高腰阔腿裤 女款', s: 'hm-wide-leg-pants-women', b: 'H&M', d: '垂坠感面料，高腰显瘦，通勤休闲', p: 199 },
    { t: 'UR 小香风外套 女款', s: 'ur-tweed-jacket-women', b: 'UR', d: '粗花呢面料，金属纽扣，法式优雅', p: 499, mp: 699 },
    { t: '伊芙丽 真丝衬衫 女款', s: 'eifini-silk-blouse-women', b: '伊芙丽', d: '桑蚕丝面料，飘带领设计，通勤优雅', p: 599 },
    { t: 'MO&Co. 高腰牛仔短裤', s: 'moandco-denim-shorts-women', b: 'MO&Co.', d: '毛边设计，纯棉水洗，显腿长', p: 399 },
    { t: '三彩 气质连体裤 女款', s: 'sancai-jumpsuit-women', b: '三彩', d: '西装领收腰，垂感面料，通勤OL风', p: 499 },
    { t: '欧时力 双面羊毛大衣', s: 'ochirly-wool-coat-women', b: '欧时力', d: '双面呢工艺，中长款，手缝翻驳领', p: 1999, mp: 2999 },
    { t: 'ONLY 碎花半身裙 女款', s: 'only-floral-skirt-women', b: 'ONLY', d: '雪纺碎花，松紧腰A字裙，浪漫飘逸', p: 199, mp: 299 },
    { t: 'VERO MODA 风衣外套 女款', s: 'vero-moda-trench-women', b: 'VERO MODA', d: '双排扣中长款，腰带收腰，经典卡其', p: 699, mp: 899 },
    { t: '乐町 圆领套头毛衣 女款', s: 'lehoo-sweater-women', b: '乐町', d: '柔软混纺，纯色百搭，宽松慵懒风', p: 199 },
    { t: '拉夏贝尔 雪纺上衣 女款', s: 'lachapelle-chiffon-top-women', b: '拉夏贝尔', d: '荷叶边设计，轻薄透气，优雅通勤', p: 239 },
    { t: '江南布衣 棉麻连衣裙', s: 'jnby-linen-dress-women', b: 'JNBY', d: '天然棉麻，文艺复古，宽松A字版型', p: 799, mp: 999 },
    { t: '歌莉娅 针织连衣裙 女款', s: 'goelia-knit-dress-women', b: '歌莉娅', d: '修身版型，弹力针织，优雅OL风', p: 499 },
    { t: 'COS 极简背心连衣裙', s: 'cos-minimal-slip-dress', b: 'COS', d: '缎面质感，V领吊带，极简设计', p: 599 },
    { t: 'Massimo Dutti 羊绒毛衣 女款', s: 'massimo-dutti-cashmere-women', b: 'Massimo Dutti', d: '100%羊绒，圆领经典，柔软亲肤', p: 1299 },
    { t: '鄂尔多斯 羊绒衫 女款', s: 'erdos-cashmere-women', b: '鄂尔多斯', d: '内蒙古山羊绒，半高领，经典纯色', p: 1599, mp: 2199 },
    { t: 'JNBY 设计师风衣 女款', s: 'jnby-designer-trench-women', b: 'JNBY', d: '不对称剪裁，棉质面料，先锋设计', p: 1299, mp: 1799 },
  ]},

  // ── 鞋靴 (17 more → 20 total) ──
  { catSlug: 'shoes', bg: '92400E', products: [
    { t: 'Nike Air Force 1 07', s: 'nike-air-force-1-07', b: 'Nike', d: '经典空军一号，全白皮面，百搭之王', p: 799 },
    { t: 'Adidas Samba OG', s: 'adidas-samba-og', b: 'Adidas', d: '复古德训鞋，翻毛皮拼接，街头潮流', p: 799 },
    { t: 'ASICS GEL-KAYANO 30', s: 'asics-gel-kayano-30', b: 'ASICS', d: '4D引导稳定，FF BLAST+中底，支撑跑鞋', p: 1190 },
    { t: '李宁 超轻20 跑步鞋', s: 'lining-ultralight-20', b: '李宁', d: '轻弹科技中底，透气鞋面，日常慢跑', p: 499 },
    { t: '安踏 C37 3.0 软跑鞋', s: 'anta-c37-3-softrun', b: '安踏', d: 'A-FlashFoam中底，软弹舒适，通勤跑步', p: 299 },
    { t: '斯凯奇 D\'Lites 熊猫鞋', s: 'skechers-dlites-panda', b: 'Skechers', d: '经典黑白配色，记忆棉鞋垫，增高厚底', p: 499 },
    { t: '匹克 态极3.0 跑鞋', s: 'peak-taichi-3', b: '匹克', d: 'P4U自适应中底，软弹科技，休闲运动', p: 369 },
    { t: '鬼冢虎 Mexico 66', s: 'onitsuka-tiger-mexico-66', b: 'Onitsuka Tiger', d: '经典虎爪纹，真皮鞋面，日系复古', p: 790 },
    { t: 'Timberland 经典6英寸黄靴', s: 'timberland-6inch-boot', b: 'Timberland', d: '防水小麦色麂皮，钢制鞋眼，经典工装', p: 1399 },
    { t: 'Dr. Martens 1460 马丁靴', s: 'dr-martens-1460', b: 'Dr. Martens', d: '8孔经典，硬皮光面，气垫鞋底', p: 1299 },
    { t: 'UGG 经典短靴 Classic Mini', s: 'ugg-classic-mini-2', b: 'UGG', d: '双面羊皮毛一体，Treadlite轻便鞋底', p: 1080 },
    { t: '百丽 尖头高跟鞋 女款', s: 'belle-pointed-heels', b: '百丽', d: '羊皮面，细跟7cm，职场通勤优雅', p: 599, mp: 799 },
    { t: '思加图 乐福鞋 女款', s: 'staccato-loafer-women', b: '思加图', d: '牛皮软底，一脚蹬，英伦学院风', p: 699 },
    { t: 'Clarks 其乐 休闲皮鞋 男款', s: 'clarks-casual-leather-men', b: 'Clarks', d: 'Cushion Plus鞋垫，牛皮鞋面，舒适通勤', p: 799 },
    { t: 'ECCO 爱步 商务德比鞋', s: 'ecco-derby-shoes-men', b: 'ECCO', d: 'FLUIDFORM直注工艺，小牛皮，正装商务', p: 1599 },
    { t: 'Birkenstock 勃肯 Arizona 凉拖', s: 'birkenstock-arizona', b: 'Birkenstock', d: '经典双扣带，软木鞋床，天然皮革', p: 699 },
    { t: 'Crocs 经典洞洞鞋', s: 'crocs-classic-clog', b: 'Crocs', d: 'Croslite泡沫材质，轻便透气，可插鞋花', p: 299 },
  ]},

  // ── 零食 (17 more → 20 total) ──
  { catSlug: 'snacks', bg: '22C55E', products: [
    { t: '卫龙 大面筋 辣条 106g×10', s: 'weilong-latiao-10pack', b: '卫龙', d: '经典辣条，香辣过瘾，童年味道', p: 19.9 },
    { t: '旺旺 大礼包 680g', s: 'want-want-gift-box-680', b: '旺旺', d: '雪饼仙贝小馒头组合，送礼聚会', p: 39.9, mp: 59.9 },
    { t: '洽洽 瓜子 焦糖味 500g', s: 'qiaqia-sunflower-seeds-caramel', b: '洽洽', d: '焦糖味葵花子，饱满大颗粒，追剧零食', p: 15.9 },
    { t: '盐津铺子 蜜饯果干礼盒', s: 'yanjinpuzi-dried-fruit-box', b: '盐津铺子', d: '芒果干+草莓干+山楂组合，独立包装', p: 39.9 },
    { t: '来伊份 猪肉脯 200g', s: 'lyfen-pork-jerky-200g', b: '来伊份', d: '炭烤猪肉脯，原味/辣味，高蛋白零食', p: 29.9, mp: 39.9 },
    { t: '乐事 薯片 原味 104g×6', s: 'lays-chips-original-6pack', b: '乐事', d: '经典原味薯片，薄脆口感，聚会分享', p: 29.9 },
    { t: '奥利奥 夹心饼干 巧克力味 388g', s: 'oreo-chocolate-388g', b: '奥利奥', d: '扭一扭舔一舔泡一泡，经典巧克力', p: 15.9 },
    { t: '好丽友 巧克力派 12枚', s: 'orion-choco-pie-12', b: '好丽友', d: '棉花糖夹心，巧克力涂层，香甜松软', p: 19.9 },
    { t: '徐福记 沙琪玛 469g', s: 'hsu-fu-chi-sachima-469', b: '徐福记', d: '蛋酥味沙琪玛，松软可口，早餐零食', p: 15.9 },
    { t: '不二家 棒棒糖 果味 20支', s: 'fujiya-lollipop-20', b: '不二家', d: '日本进口，多种水果味，可爱造型', p: 25.9 },
    { t: '费列罗 金莎巧克力 T30 375g', s: 'ferrero-rocher-t30', b: '费列罗', d: '意大利榛果巧克力，金箔包装，送礼优选', p: 89.9 },
    { t: '德芙 丝滑牛奶巧克力 252g', s: 'dove-milk-chocolate-252', b: '德芙', d: '丝滑口感，纯可可脂，经典牛奶味', p: 39.9 },
    { t: '三只松鼠 手撕面包 1kg', s: 'three-squirrels-bread-1kg', b: '三只松鼠', d: '绵软拉丝，早餐代餐，独立小包', p: 29.9 },
    { t: '良品铺子 麻辣花生 210g×3', s: 'bestore-spicy-peanuts-3pack', b: '良品铺子', d: '四川花椒+干辣椒，酥脆花生仁', p: 25.9 },
    { t: '周黑鸭 锁鲜鸭脖 200g', s: 'zhou-hei-ya-duck-neck-200', b: '周黑鸭', d: '甜辣鲜香，锁鲜装，卤味经典', p: 29.9 },
    { t: '绝味 鸭掌 卤味 200g', s: 'juewei-duck-feet-200', b: '绝味', d: '麻辣卤鸭掌，Q弹有嚼劲，佐餐零嘴', p: 25.9 },
    { t: '卫龙 魔芋爽 素毛肚 20包', s: 'weilong-konjac-20pack', b: '卫龙', d: '香辣素毛肚，低卡解馋，嚼劲十足', p: 19.9 },
  ]},

  // ── 饮料 (17 more → 20 total) ──
  { catSlug: 'drinks', bg: '0D9488', products: [
    { t: '星巴克 星选即饮咖啡 拿铁 270ml×6', s: 'starbucks-rtd-latte-6', b: '星巴克', d: '阿拉比卡咖啡+牛乳，即开即饮', p: 59.9 },
    { t: '可口可乐 经典 330ml×24罐', s: 'coca-cola-classic-24', b: '可口可乐', d: '经典原味，清爽畅饮，聚会必备', p: 49.9 },
    { t: '百事可乐 无糖 330ml×24罐', s: 'pepsi-zero-24', b: '百事', d: '零糖零卡，经典可乐味，无负担', p: 49.9 },
    { t: '东方树叶 青柑普洱 500ml×15', s: 'oriental-leaf-puer-15', b: '农夫山泉', d: '0糖0脂0卡，青柑普洱，茶香回甘', p: 59.9 },
    { t: '三得利 乌龙茶 500ml×15', s: 'suntory-oolong-15', b: '三得利', d: '无糖乌龙茶，茶多酚丰富，日本工艺', p: 49.9 },
    { t: '王老吉 凉茶 310ml×24', s: 'wang-lao-ji-24', b: '王老吉', d: '经典凉茶，怕上火喝王老吉', p: 69.9 },
    { t: '红牛 维生素功能饮料 250ml×24', s: 'red-bull-250-24', b: '红牛', d: '牛磺酸+维生素B族，提神抗疲劳', p: 139 },
    { t: '怡宝 纯净水 555ml×24', s: 'cestbon-water-24', b: '怡宝', d: '纯净水，二次反渗透，口感纯净', p: 24.9 },
    { t: '百岁山 天然矿泉水 348ml×24', s: 'ganten-water-348-24', b: '百岁山', d: '天然矿泉水，偏硅酸型，水源地直供', p: 39.9 },
    { t: '安慕希 原味酸奶 205g×12', s: 'ambrosial-yogurt-12', b: '伊利', d: '希腊风味酸奶，浓郁醇厚，优质蛋白', p: 59.9 },
    { t: '特仑苏 纯牛奶 250ml×12', s: 'telunsu-milk-12', b: '蒙牛', d: '3.6g优质乳蛋白，更好的牛奶', p: 69.9 },
    { t: '莫斯利安 原味酸奶 200g×12', s: 'momchilovtsi-yogurt-12', b: '光明', d: '保加利亚菌种发酵，常温酸奶先驱', p: 49.9 },
    { t: '椰树 椰汁 245ml×24', s: 'coconut-palm-juice-24', b: '椰树', d: '海南新鲜椰肉榨取，不加香精色素', p: 89.9 },
    { t: '汇源 100%橙汁 1L×6', s: 'huiyuan-orange-juice-6', b: '汇源', d: '100%纯果汁，无添加糖，营养早餐', p: 49.9 },
    { t: '维他柠檬茶 250ml×24', s: 'vita-lemon-tea-24', b: '维他', d: '真茶真柠檬，涩涩的才好喝', p: 59.9 },
    { t: '加多宝 凉茶 310ml×24', s: 'jdb-herbal-tea-24', b: '加多宝', d: '凉茶领导者，清热降火，甘甜可口', p: 69.9 },
    { t: '养乐多 活性乳酸菌 100ml×25', s: 'yakult-probiotic-25', b: '养乐多', d: '代田菌活性乳酸菌，每瓶100亿益生菌', p: 39.9 },
  ]},

  // ── 生鲜 (17 more → 20 total) ──
  { catSlug: 'fresh', bg: '16A34A', products: [
    { t: '新疆阿克苏冰糖心苹果 5kg', s: 'aksu-apple-5kg', b: '新疆果园', d: '正宗冰糖心，果核透明，脆甜多汁', p: 59.9 },
    { t: '云南蓝莓 125g×6盒', s: 'yunnan-blueberry-6box', b: '佳沃', d: '云南高原蓝莓，颗颗饱满，花青素丰富', p: 79.9 },
    { t: '海南金煌芒果 5斤', s: 'hainan-mango-5lb', b: '热带鲜果', d: '海南金煌大芒果，核小肉厚，香甜浓郁', p: 49.9 },
    { t: '山东大樱桃 美早 2斤', s: 'shandong-cherry-2lb', b: '烟台果农', d: '烟台美早大樱桃，果径26mm+，脆甜', p: 79.9 },
    { t: '赣南脐橙 10斤装', s: 'gannan-navel-orange-10lb', b: '赣南橙农', d: '赣南脐橙，薄皮多汁，维C丰富', p: 49.9 },
    { t: '泰国金枕头榴莲 整果 约5斤', s: 'thai-durian-musang-king', b: '热带鲜果', d: '泰国金枕头，软糯甘甜，果肉饱满', p: 199, mp: 299 },
    { t: '澳洲和牛 M5级 眼肉牛排 200g×2', s: 'aussie-wagyu-m5-ribeye', b: '牛排工坊', d: '澳洲谷饲和牛M5级，大理石花纹，入口即化', p: 199, mp: 299 },
    { t: '科尔沁 牛腱子肉 1kg', s: 'kerchin-beef-shank-1kg', b: '科尔沁', d: '内蒙古草饲牛，筋肉相间，适合卤炖', p: 89.9 },
    { t: '正大 鸡胸肉 冷冻 1kg', s: 'cp-chicken-breast-1kg', b: '正大', d: '泰国CP正大，高蛋白低脂肪，健身必备', p: 29.9 },
    { t: '獐子岛 即食鲍鱼 6只装', s: 'zoneco-abalone-6pcs', b: '獐子岛', d: '大连鲍鱼，即食方便，Q弹鲜美', p: 99.9 },
    { t: '挪威三文鱼 刺身级 200g', s: 'norway-salmon-sashimi-200g', b: '鲜享', d: '挪威冰鲜空运，刺身级品质，肉质紧实', p: 79.9 },
    { t: '黑虎虾 大号 400g 16-20只', s: 'black-tiger-shrimp-400g', b: '海鲜汇', d: '东南亚黑虎虾，壳薄肉厚，Q弹鲜美', p: 69.9 },
    { t: '波士顿龙虾 鲜活 约1斤', s: 'boston-lobster-live-1lb', b: '海鲜汇', d: '加拿大鲜活波龙，现捞现发，蒜蓉必备', p: 169, mp: 219 },
    { t: '阳澄湖大闸蟹 公4两母3两 4对', s: 'yangcheng-crab-4pairs', b: '蟹太太', d: '正宗阳澄湖，防伪戒指，蟹膏丰满', p: 399, mp: 599 },
    { t: '有机蔬菜 混合套装 8种 3kg', s: 'organic-veggie-mix-3kg', b: '绿色农场', d: '有机认证，8种时令蔬菜搭配，新鲜配送', p: 69.9 },
    { t: '东北五常大米 稻花香2号 10kg', s: 'wuchang-rice-10kg', b: '十月稻田', d: '五常稻花香，当季新米，颗粒饱满', p: 69.9 },
    { t: '金龙鱼 菜籽油 5L', s: 'arowana-rapeseed-oil-5l', b: '金龙鱼', d: '非转基因菜籽，物理压榨，浓香风味', p: 59.9 },
  ]},

  // ── 护肤 (17 more → 20 total) ──
  { catSlug: 'skincare', bg: 'F472B6', products: [
    { t: '资生堂 红妍肌活精华 75ml', s: 'shiseido-ultimune-75ml', b: '资生堂', d: '免疫力精华，强韧肌肤，抗老维稳', p: 790 },
    { t: '海蓝之谜 精华面霜 30ml', s: 'la-mer-moisturizing-cream-30', b: 'La Mer', d: '神奇活性精萃Miracle Broth，修护焕新', p: 2380 },
    { t: '修丽可 CE精华 30ml', s: 'skinceuticals-ce-ferulic-30', b: '修丽可', d: '15%维C+1%维E+阿魏酸，抗氧化标杆', p: 1350 },
    { t: '欧莱雅 复颜玻尿酸面膜 5片', s: 'loreal-ha-mask-5pcs', b: "L'Oreal", d: '三重玻尿酸，深层补水，急救保湿', p: 79.9 },
    { t: '珀莱雅 双抗精华2.0 30ml', s: 'proya-double-anti-serum-30', b: '珀莱雅', d: '抗糖抗氧双抗，烟酰胺+虾青素', p: 249 },
    { t: '薇诺娜 舒敏保湿特护霜 50g', s: 'winona-soothing-cream-50g', b: '薇诺娜', d: '敏感肌专用，马齿苋精华，修护屏障', p: 268 },
    { t: '玉兰油 大红瓶面霜 50g', s: 'olay-regenerist-cream-50g', b: 'Olay', d: '烟酰胺+胜肽，淡纹紧致，性价比抗老', p: 249 },
    { t: '科颜氏 高保湿面霜 50ml', s: 'kiehls-ultra-cream-50ml', b: "Kiehl's", d: '角鲨烷+冰川蛋白，24小时长效保湿', p: 380 },
    { t: '悦木之源 菌菇水 200ml', s: 'origins-mushroom-lotion-200', b: 'Origins', d: '灵芝+冬虫夏草，维稳修护，健康水光', p: 310 },
    { t: '百雀羚 水嫩精纯面霜 50g', s: 'pechoin-aqua-cream-50g', b: '百雀羚', d: '国货经典，草本精华，保湿滋润', p: 99 },
    { t: '自然堂 小紫瓶精华 50ml', s: 'chando-purple-serum-50ml', b: '自然堂', d: '喜马拉雅冰肌水，烟酰胺亮肤', p: 199 },
    { t: '相宜本草 红景天焕亮精华 30ml', s: 'inoherb-rhodiola-serum-30', b: '相宜本草', d: '红景天+灵芝，提亮暗沉，匀净肤色', p: 139 },
    { t: '芙丽芳丝 净润洗面霜 120g', s: 'freeplus-face-wash-120g', b: '芙丽芳丝', d: '氨基酸洁面，温和不紧绷，敏感肌可用', p: 150 },
    { t: '理肤泉 B5修复面霜 40ml', s: 'la-roche-posay-b5-balm-40', b: '理肤泉', d: '维生素B5+积雪草苷，修护舒缓', p: 228 },
    { t: '倩碧 黄油 Moisturizing Lotion 125ml', s: 'clinique-ddml-125ml', b: '倩碧', d: '三步曲经典黄油，清爽保湿，油皮也爱', p: 290 },
    { t: '娇兰 复原蜜 30ml', s: 'guerlain-abeille-royale-30', b: '娇兰', d: '蜂皇精萃，修护+抗老，奢华护肤', p: 890 },
    { t: '赫莲娜 黑绷带面霜 50ml', s: 'helena-rubinstein-cream-50', b: '赫莲娜', d: '30%玻色因，顶级抗老，奢华修护', p: 3180 },
  ]},

  // ── 彩妆 (17 more → 20 total) ──
  { catSlug: 'makeup', bg: 'DB2777', products: [
    { t: 'YSL 黑管唇釉 #12', s: 'ysl-vinyl-lip-stain-12', b: 'YSL', d: '镜面光泽唇釉，高饱和色彩，持久显色', p: 320 },
    { t: '迪奥 锁妆粉底液 2N', s: 'dior-forever-foundation-2n', b: 'Dior', d: '24h持妆，哑光雾面，控油不暗沉', p: 490 },
    { t: '阿玛尼 权力粉底液 #4', s: 'armani-power-fabric-4', b: 'Armani', d: '微粉膜技术，轻薄遮瑕，自然奶油肌', p: 580 },
    { t: 'NARS 裸光蜜粉饼 Crystal', s: 'nars-light-reflecting-powder', b: 'NARS', d: '柔焦控油，裸光肌感，便携补妆', p: 380 },
    { t: '兰蔻 菁纯气垫 PO-01', s: 'lancome-cushion-po01', b: '兰蔻', d: '长效持妆，水润遮瑕，玫瑰精华', p: 520 },
    { t: 'Tom Ford 四色眼影 Nude Dip', s: 'tom-ford-eyeshadow-nude-dip', b: 'Tom Ford', d: '四色搭配，丝绒雾面+珠光，高级配色', p: 620 },
    { t: 'CT Pillow Talk 唇膏', s: 'ct-pillow-talk-lipstick', b: 'Charlotte Tilbury', d: '全球断货色，裸粉色系，丝滑质地', p: 280 },
    { t: '橘朵 腮红 哑光 #211', s: 'judydoll-blush-211', b: '橘朵', d: '超细粉质，自然红晕，多色可选', p: 29.9 },
    { t: '毛戈平 柔光收颜粉膏', s: 'maogeping-cream-contour', b: '毛戈平', d: '膏状修容，自然阴影，大师配色', p: 190 },
    { t: '卡姿兰 大眼睛睫毛膏', s: 'carslan-mascara-big-eye', b: '卡姿兰', d: '纤长卷翘，不晕染，防水速干', p: 69 },
    { t: '美宝莲 FIT ME粉底液 120', s: 'maybelline-fitme-120', b: '美宝莲', d: '柔雾哑光，12h控油，自然贴肤', p: 99 },
    { t: 'Bobbi Brown 虫草粉底液', s: 'bobbi-brown-skin-foundation', b: 'Bobbi Brown', d: '虫草精华养肤，自然光泽，8h持妆', p: 480 },
    { t: '植村秀 砍刀眉笔 #02', s: 'shu-uemura-brow-sword-02', b: '植村秀', d: '扁平刀型笔芯，根根分明，自然眉形', p: 230 },
    { t: '3CE 丝绒唇釉 #TAUPE', s: '3ce-velvet-lip-tint-taupe', b: '3CE', d: '雾面丝绒质感，高显色，枫叶色系', p: 99 },
    { t: '珂拉琪 空气唇泥 #106', s: 'colorkey-lip-mud-106', b: '珂拉琪', d: '雾面唇泥，轻盈不拔干，高级哑光', p: 59.9 },
    { t: 'KATE 三色眉粉 EX-5', s: 'kate-brow-powder-ex5', b: 'KATE', d: '自然渐变，阴影鼻影一盒搞定', p: 69 },
    { t: 'Canmake 棉花糖控油蜜粉饼', s: 'canmake-marshmallow-powder', b: 'Canmake', d: '控油定妆，棉花糖粉扑，日本人气', p: 69 },
  ]},

  // ── 洗护 (17 more → 20 total) ──
  { catSlug: 'wash-care', bg: '06B6D4', products: [
    { t: '海飞丝 去屑洗发水 750ml', s: 'head-shoulders-750ml', b: '海飞丝', d: '去屑止痒，ZPT因子，清爽控油', p: 49.9 },
    { t: '清扬 男士洗发水 控油 720ml', s: 'clear-men-shampoo-720ml', b: '清扬', d: '男士控油去屑，氨基酸配方，清爽', p: 39.9 },
    { t: '沙宣 修护水养洗发水 750ml', s: 'vidal-sassoon-repair-750ml', b: '沙宣', d: '角蛋白修护，干枯受损发质专用', p: 49.9 },
    { t: '吕 红吕洗发水 500ml', s: 'ryoe-red-shampoo-500ml', b: '吕', d: '韩方含光耀护，受损发质修护', p: 69.9 },
    { t: '力士 沐浴露 玫瑰香 1L', s: 'lux-body-wash-rose-1l', b: '力士', d: '法国玫瑰精油，持久留香，丝滑肌肤', p: 39.9 },
    { t: '多芬 滋养美肤沐浴乳 1L', s: 'dove-body-wash-nourish-1l', b: '多芬', d: '1/4保湿乳，温和滋养，肌肤不紧绷', p: 39.9 },
    { t: '六神 清凉沐浴露 750ml', s: 'liushen-cooling-body-wash', b: '六神', d: '冰凉薄荷，夏季清爽，持久清凉', p: 29.9 },
    { t: '威露士 消毒液 1L', s: 'walch-disinfectant-1l', b: '威露士', d: '有效杀灭99.999%细菌，衣物家居消毒', p: 39.9 },
    { t: '蓝月亮 洗衣液 3kg', s: 'bluemoon-laundry-liquid-3kg', b: '蓝月亮', d: '深层洁净，亮白增艳，薰衣草香', p: 49.9 },
    { t: '奥妙 洗衣凝珠 50颗', s: 'omo-laundry-pods-50', b: '奥妙', d: '三腔浓缩，一颗搞定一桶衣服', p: 59.9 },
    { t: '立白 洗洁精 1.5kg', s: 'liby-dish-soap-1500ml', b: '立白', d: '食品级配方，强效去油，不伤手', p: 12.9 },
    { t: '碧柔 水活防晒霜 SPF50 50ml', s: 'biore-uv-aqua-rich-50ml', b: '碧柔', d: 'SPF50+ PA++++，水感轻薄，日常防晒', p: 59.9 },
    { t: '妮维雅 男士控油洁面乳 150g', s: 'nivea-men-face-wash-150g', b: '妮维雅', d: '深层控油，清爽不紧绷，男士专用', p: 39.9 },
    { t: '高露洁 牙膏 360°全面口腔 180g', s: 'colgate-360-toothpaste-180g', b: '高露洁', d: '360°清洁，防蛀固齿，清新口气', p: 15.9 },
    { t: '佳洁士 3D炫白牙膏 180g', s: 'crest-3d-white-180g', b: '佳洁士', d: '美白因子，去除牙渍，闪亮微笑', p: 19.9 },
    { t: '舒客 电动牙刷 G33', s: 'saky-electric-toothbrush-g33', b: '舒客', d: '声波震动31000次/分，4种模式，IPX7', p: 199 },
    { t: '狮王 漱口水 450ml', s: 'lion-mouthwash-450ml', b: '狮王', d: '温和不辣口，清新口气，减少牙菌斑', p: 29.9 },
  ]},

  // ── 文学 (17 more → 20 total) ──
  { catSlug: 'literature', bg: '5B21B6', products: [
    { t: '人生海海（麦家）', s: 'life-is-like-sea-maijia', b: '北京十月文艺', d: '麦家2019长篇小说，一个人一生的命运浮沉', p: 39.8 },
    { t: '额尔古纳河右岸（迟子建）', s: 'ergun-river-right-bank', b: '人民文学出版社', d: '茅盾文学奖获奖作品，鄂温克族百年史诗', p: 39 },
    { t: '围城（钱钟书）', s: 'fortress-besieged', b: '人民文学出版社', d: '钱钟书经典讽刺小说，城外的人想进去', p: 35 },
    { t: '红楼梦（曹雪芹）', s: 'dream-of-red-mansions', b: '人民文学出版社', d: '四大名著之首，中国古典文学巅峰', p: 59.7 },
    { t: '平凡的世界（路遥）全三册', s: 'ordinary-world-trilogy', b: '北京十月文艺', d: '路遥代表作，展现普通人的不普通人生', p: 68 },
    { t: '挪威的森林（村上春树）', s: 'norwegian-wood-murakami', b: '上海译文出版社', d: '村上春树经典恋爱小说，青春与丧失', p: 32 },
    { t: '小王子（圣埃克苏佩里）', s: 'the-little-prince', b: '人民文学出版社', d: '世界经典童话，献给大人的寓言故事', p: 22 },
    { t: '追风筝的人（胡赛尼）', s: 'the-kite-runner', b: '上海人民出版社', d: '为你，千千万万遍，阿富汗友情史诗', p: 35 },
    { t: '解忧杂货店（东野圭吾）', s: 'miracles-of-namiya-store', b: '南海出版公司', d: '东野圭吾温情之作，三个时空交错的治愈', p: 39.5 },
    { t: '白夜行（东野圭吾）', s: 'journey-under-midnight-sun', b: '南海出版公司', d: '东野圭吾巅峰悬疑，绝望中的爱与救赎', p: 39.5 },
    { t: '月亮与六便士（毛姆）', s: 'moon-and-sixpence', b: '上海译文出版社', d: '以高更为原型，理想与现实的永恒命题', p: 25 },
    { t: '局外人（加缪）', s: 'the-stranger-camus', b: '上海译文出版社', d: '存在主义经典，荒诞世界中的反叛', p: 22 },
    { t: '1984（乔治·奥威尔）', s: '1984-george-orwell', b: '北京十月文艺', d: '反乌托邦三部曲之一，极权社会警示录', p: 28 },
    { t: '了不起的盖茨比（菲茨杰拉德）', s: 'the-great-gatsby', b: '上海译文出版社', d: '爵士时代的美国梦幻灭，文学经典', p: 22 },
    { t: '杀死一只知更鸟（哈珀·李）', s: 'to-kill-a-mockingbird', b: '译林出版社', d: '普利策奖作品，正义与偏见的较量', p: 35 },
    { t: '霍乱时期的爱情（马尔克斯）', s: 'love-in-time-of-cholera', b: '南海出版公司', d: '世间有多少爱情，就有多少种讲述', p: 42 },
    { t: '生死疲劳（莫言）', s: 'life-and-death-moyan', b: '上海文艺出版社', d: '莫言诺贝尔代表作，中国农村50年变迁', p: 49 },
  ]},

  // ── 教育 (17 more → 20 total) ──
  { catSlug: 'education', bg: '2563EB', products: [
    { t: '线性代数（同济第六版）', s: 'linear-algebra-tongji-6th', b: '高等教育出版社', d: '同济大学数学系编，高校经典教材', p: 32 },
    { t: '大学英语四级真题 2024版', s: 'cet4-past-papers-2024', b: '外语教学与研究出版社', d: '近10年真题详解，赠听力音频', p: 39.8 },
    { t: '考研政治全真模拟 2025', s: 'kaoyan-politics-mock-2025', b: '高等教育出版社', d: '肖秀荣考研政治冲刺8套卷', p: 29.8 },
    { t: '剑桥雅思真题集 18', s: 'cambridge-ielts-18', b: '外语教学与研究出版社', d: '官方真题，含听力音频，备考必备', p: 58 },
    { t: '新概念英语 全四册', s: 'new-concept-english-full', b: '外语教学与研究出版社', d: '经典英语教材，从入门到精通', p: 88, mp: 128 },
    { t: '数据结构 C语言版（严蔚敏）', s: 'data-structure-c-yan', b: '清华大学出版社', d: '计算机专业核心教材，考研408必备', p: 39 },
    { t: '操作系统概念 第十版', s: 'os-concepts-10th', b: '机械工业出版社', d: '恐龙书，操作系统权威教材', p: 89 },
    { t: '计算机网络 自顶向下方法 第八版', s: 'computer-networking-8th', b: '机械工业出版社', d: 'Kurose经典教材，自顶向下讲解网络', p: 99 },
    { t: '深入理解计算机系统 CSAPP 第三版', s: 'csapp-3rd', b: '机械工业出版社', d: 'CMU镇校之宝，程序员进阶必读', p: 139 },
    { t: '算法导论 第四版', s: 'intro-to-algorithms-4th', b: '机械工业出版社', d: 'CLRS经典算法教材，理论与实践并重', p: 128 },
    { t: '机器学习（周志华）西瓜书', s: 'machine-learning-zhou', b: '清华大学出版社', d: 'AI入门经典教材，深入浅出讲解ML', p: 68 },
    { t: '统计学习方法（李航）第二版', s: 'statistical-learning-li', b: '清华大学出版社', d: '机器学习理论基础，NLP/CV从业者必读', p: 58 },
    { t: 'C++ Primer 第5版 中文版', s: 'cpp-primer-5th', b: '电子工业出版社', d: 'C++11/14标准，入门到精通，经典权威', p: 108 },
    { t: 'Effective Java 中文版 第三版', s: 'effective-java-3rd', b: '机械工业出版社', d: 'Java编程最佳实践，Bloch经典之作', p: 89 },
    { t: '设计模式 GoF 经典版', s: 'design-patterns-gof', b: '机械工业出版社', d: '四人帮经典设计模式，面向对象圣经', p: 69 },
    { t: 'SQL必知必会 第五版', s: 'sql-in-10-minutes-5th', b: '人民邮电出版社', d: '10分钟SQL入门，快速掌握数据库操作', p: 49 },
    { t: 'Head First 设计模式 第二版', s: 'head-first-design-patterns-2nd', b: '中国电力出版社', d: '图文并茂讲解设计模式，轻松易懂', p: 79 },
  ]},

  // ── 漫画 (17 more → 20 total) ──
  { catSlug: 'comic', bg: 'DC2626', products: [
    { t: '火影忍者 全72卷 套装', s: 'naruto-manga-1-72', b: '连环画出版社', d: '岸本�的马斯特著，忍者世界的羁绊与梦想', p: 5.9, mp: 599 },
    { t: '灌篮高手 完全版 1-24', s: 'slam-dunk-complete-1-24', b: '长春出版社', d: '井上雄彦经典，教练我想打篮球', p: 9.9, mp: 499 },
    { t: '龙珠 完全版 1-34', s: 'dragon-ball-complete-1-34', b: '中少总社', d: '鸟山明经典，影响全球的少年漫画', p: 6.9, mp: 699 },
    { t: '名侦探柯南 1-104卷', s: 'detective-conan-1-104', b: '长春出版社', d: '青山刚昌推理漫画，真相永远只有一个', p: 5.9, mp: 399 },
    { t: 'JOJO的奇妙冒险 第一部~第八部', s: 'jojo-bizarre-adventure', b: '北京中少总社', d: '�的木飞吕彦著，跨越百年的命运之战', p: 9.9, mp: 899 },
    { t: '银魂 1-77卷', s: 'gintama-manga-1-77', b: '连环画出版社', d: '空知英秋著，搞笑与热血并存的武士物语', p: 5.9, mp: 399 },
    { t: '东京喰种 全14卷', s: 'tokyo-ghoul-1-14', b: '天闻角川', d: '石田翠著，人与喰种的悲剧命运', p: 9.9, mp: 199 },
    { t: '咒术回战 1-24卷', s: 'jujutsu-kaisen-1-24', b: '湖南美术出版社', d: '芥见下下著，呪灵与咒术师的战斗', p: 6.9, mp: 299 },
    { t: '电锯人 1-16卷', s: 'chainsaw-man-1-16', b: '浙江人民美术出版社', d: '藤本树著，暗黑系少年漫画新标杆', p: 6.9, mp: 199 },
    { t: '间谍过家家 1-13卷', s: 'spy-x-family-1-13', b: '浙江人民美术出版社', d: '远藤达哉著，伪装家庭的温馨喜剧', p: 7.9, mp: 149 },
    { t: '排球少年 1-45卷', s: 'haikyuu-manga-1-45', b: '长春出版社', d: '古馆春一著，排球青春热血物语', p: 5.9, mp: 399 },
    { t: '我的英雄学院 1-39卷', s: 'my-hero-academia-1-39', b: '湖南美术出版社', d: '堀越耕平著，每个人都能成为英雄', p: 6.9, mp: 399 },
    { t: '约定的梦幻岛 1-20卷', s: 'promised-neverland-1-20', b: '东立出版社', d: '白井カイウ著，孤儿院的惊天秘密', p: 7.9, mp: 199 },
    { t: '蓝色监狱 1-28卷', s: 'blue-lock-manga-1-28', b: '东立出版社', d: '金城宗幸著，打造世界最强前锋', p: 6.9, mp: 299 },
    { t: '宝石之国 1-12卷', s: 'land-of-lustrous-1-12', b: '东立出版社', d: '市川春子著，宝石生命体的哲学冒险', p: 9.9, mp: 149 },
    { t: '异兽魔都 1-23卷', s: 'dorohedoro-manga-1-23', b: '玉皇朝', d: '林田球著，黑暗奇幻与美食的混搭', p: 9.9, mp: 299 },
    { t: '全职猎人 1-37卷', s: 'hunter-x-hunter-1-37', b: '长春出版社', d: '富坚义博著，冒险与念能力的经典', p: 5.9, mp: 299 },
  ]},

  // ── 健身器材 (17 more → 20 total) ──
  { catSlug: 'fitness', bg: '0D9488', products: [
    { t: '迪卡侬 跑步机 Run 520', s: 'decathlon-treadmill-run520', b: '迪卡侬', d: '家用可折叠，10km/h，减震跑台', p: 2499 },
    { t: '舒华 椭圆机 SH-B8200T', s: 'shuhua-elliptical-b8200', b: '舒华', d: '静音磁控，16档阻力，心率监测', p: 2999 },
    { t: '麦瑞克 水阻划船机 Merach', s: 'merach-water-rower', b: '麦瑞克', d: '进口白蜡木，真实划水感，折叠收纳', p: 2699 },
    { t: '运动伙伴 壶铃 12kg', s: 'sport-buddy-kettlebell-12kg', b: '运动伙伴', d: '包胶壶铃，防滑握把，力量训练', p: 99, mp: 199 },
    { t: '迪卡侬 弹力带 套装 5条', s: 'decathlon-resistance-bands-5', b: '迪卡侬', d: '5种阻力级别，天然乳胶，居家健身', p: 49.9 },
    { t: '迪卡侬 瑜伽球 防爆 65cm', s: 'decathlon-yoga-ball-65cm', b: '迪卡侬', d: '加厚防爆，承重300kg，附带气泵', p: 69.9 },
    { t: '云麦 筋膜枪 Pro Max', s: 'yunmai-massage-gun-pro-max', b: '云麦', d: '无刷电机，6档调速，4种按摩头', p: 399 },
    { t: 'Keep 智能跳绳 SR3', s: 'keep-smart-rope-sr3', b: 'Keep', d: '自动计数，蓝牙连接App，轴承顺滑', p: 149 },
    { t: '迪卡侬 健身手套 加厚', s: 'decathlon-training-gloves', b: '迪卡侬', d: '硅胶防滑，透气网面，护腕设计', p: 49.9 },
    { t: '李宁 运动护膝 篮球专业', s: 'lining-knee-pad-basketball', b: '李宁', d: '高弹压缩，侧翼稳定，篮球跑步通用', p: 89 },
    { t: 'AQ 加压护腕 运动防护', s: 'aq-wrist-brace', b: 'AQ', d: '弹力加压，缠绕式设计，羽毛球网球', p: 59.9 },
    { t: '金史密斯 走步机 K15 Pro', s: 'kingsmith-walkpad-k15-pro', b: '金史密斯', d: '超薄可折叠，遥控调速，办公室走步', p: 1699 },
    { t: '海德 WalkingPad C2 折叠走步机', s: 'walkingpad-c2', b: 'WalkingPad', d: '小米生态链，180度全折叠，APP控制', p: 1399 },
    { t: '好家庭 引体向上器 门框单杠', s: 'good-family-pull-up-bar', b: '好家庭', d: '免打孔门框安装，承重200kg，多握把', p: 99 },
    { t: '万达康 仰卧板 家用健腹', s: 'wondercore-sit-up-bench', b: '万达康', d: '多角度调节，折叠收纳，全身训练', p: 299, mp: 499 },
    { t: '迪卡侬 泡沫轴 筋膜放松', s: 'decathlon-foam-roller', b: '迪卡侬', d: 'EPP高密度泡沫，肌肉放松，运动恢复', p: 49.9 },
    { t: '野小兽 磁控动感单车 S1', s: 'yesoul-spin-bike-s1', b: '野小兽', d: '磁控静音，iPad支架，在线课程', p: 1299 },
  ]},

  // ── 户外装备 (17 more → 20 total) ──
  { catSlug: 'outdoor', bg: '166534', products: [
    { t: '始祖鸟 Beta LT 冲锋衣', s: 'arcteryx-beta-lt-jacket', b: "Arc'teryx", d: 'GORE-TEX三层面料，轻量防水，全天候', p: 4500 },
    { t: '北面 1996 Nuptse 羽绒服', s: 'tnf-1996-nuptse-down', b: 'The North Face', d: '经典面包服，700蓬松度鹅绒，保暖时尚', p: 2298 },
    { t: '猛犸象 Convey 登山包 30L', s: 'mammut-convey-30l', b: 'Mammut', d: '瑞士工艺，人体工学背负，透气背板', p: 999 },
    { t: '黑钻 头灯 Spot 400', s: 'black-diamond-spot-400', b: 'Black Diamond', d: '400流明，防水IPX8，红光模式', p: 399 },
    { t: '迪卡侬 帐篷 2秒快开 3人', s: 'decathlon-tent-2sec-3p', b: '迪卡侬', d: '2秒弹开，遮光涂层，防水2000mm', p: 499, mp: 699 },
    { t: '牧高笛 睡袋 信封式 -10℃', s: 'mobi-garden-sleeping-bag', b: '牧高笛', d: '鸭绒填充，舒适温标-10℃，可拼接', p: 399 },
    { t: '骆驼 碳纤维登山杖 一对', s: 'camel-carbon-trekking-poles', b: '骆驼', d: '碳纤维杖身，三节可调，EVA握把', p: 199 },
    { t: '探路者 男款徒步鞋 防水', s: 'toread-hiking-shoes-men', b: '探路者', d: '防水透气面料，Vibram大底，减震', p: 499, mp: 699 },
    { t: 'Salomon 萨洛蒙 越野跑鞋 XT-6', s: 'salomon-xt6', b: 'Salomon', d: '高级底盘，Quicklace系统，复古越野', p: 1199 },
    { t: 'La Sportiva 攀岩鞋 Solution', s: 'la-sportiva-solution', b: 'La Sportiva', d: 'Vibram XS Edge鞋底，钩脚型，竞技攀岩', p: 1199 },
    { t: 'Sea to Summit 防水袋 20L', s: 'sea-to-summit-drybag-20l', b: 'Sea to Summit', d: '轻量防水，卷口密封，多色可选', p: 199 },
    { t: 'LifeStraw 户外净水器', s: 'lifestraw-personal-filter', b: 'LifeStraw', d: '过滤99.9999%细菌，免供电，应急净水', p: 199 },
    { t: 'Leatherman 多功能工具钳 Wave+', s: 'leatherman-wave-plus', b: 'Leatherman', d: '18种功能，420HC不锈钢，25年质保', p: 899 },
    { t: 'NEMO 充气睡垫 Tensor', s: 'nemo-tensor-sleeping-pad', b: 'NEMO', d: '超轻充气，R值3.5，20D面料', p: 899 },
    { t: 'MSR PocketRocket 2 户外炉具', s: 'msr-pocketrocket-2', b: 'MSR', d: '超轻73g，3分钟烧开1L水，折叠', p: 399 },
    { t: 'Osprey 小鹰 Kestrel 38 背包', s: 'osprey-kestrel-38', b: 'Osprey', d: '38L中型包，AirScape背板，2-3日线路', p: 1199 },
    { t: 'Gregory 格里高利 Zulu 55 背包', s: 'gregory-zulu-55', b: 'Gregory', d: '55L重装包，FreeFloat悬浮背负系统', p: 1799 },
  ]},

  // ── 运动服饰 (17 more → 20 total) ──
  { catSlug: 'sportswear', bg: '14B8A6', products: [
    { t: '李宁 韦德之道11 篮球鞋', s: 'lining-wow11-basketball', b: '李宁', d: '韦德签名系列，云减震，碳板支撑', p: 1299, mp: 1599 },
    { t: 'Air Jordan 1 Retro High OG', s: 'air-jordan-1-retro-high', b: 'Nike', d: '经典AJ1高帮，Air缓震，潮流文化图标', p: 1299, mp: 1599 },
    { t: 'Nike Dri-FIT 男士短裤', s: 'nike-drifit-shorts-men', b: 'Nike', d: '速干面料，弹力腰带，跑步训练', p: 199 },
    { t: 'Adidas 三叶草 运动长裤', s: 'adidas-originals-track-pants', b: 'Adidas', d: '经典三条纹，锥形裤腿，复古运动', p: 399 },
    { t: 'Puma RS-X Reinvention 运动鞋', s: 'puma-rsx-reinvention', b: 'Puma', d: '复古老爹鞋，Running System缓震', p: 699 },
    { t: 'FILA 运动Bra 中强度 女款', s: 'fila-sports-bra-medium', b: 'FILA', d: '中强度支撑，网纱透气，瑜伽跑步', p: 199 },
    { t: '安踏 冠军系列 连帽卫衣', s: 'anta-champion-hoodie', b: '安踏', d: '纯棉加绒，冠军刺绣Logo，宽松版', p: 299 },
    { t: '特步 竞速160X 5.0 碳板跑鞋', s: 'xtep-160x-5-carbon', b: '特步', d: '全掌碳板，动力巢PB中底，竞速马拉松', p: 999 },
    { t: '361° 飞燃3 碳板跑鞋', s: '361-feiran-3-carbon', b: '361°', d: 'QU!KFLAME中底，全掌碳板，轻量竞速', p: 699 },
    { t: '匹克 澎湃 态极大三角 跑鞋', s: 'peak-taichi-triangle', b: '匹克', d: '态极自适应中底，大三角纹路大底', p: 499 },
    { t: '鸿星尔克 奇弹3.0 跑鞋', s: 'erke-qitan-3-running', b: '鸿星尔克', d: '奇弹科技中底，轻弹回馈，国货之光', p: 299 },
    { t: 'Kappa 运动套装 男款', s: 'kappa-tracksuit-men', b: 'Kappa', d: '背靠背经典，外套+长裤套装，运动休闲', p: 599, mp: 799 },
    { t: 'Reebok Classic Leather 复古皮面', s: 'reebok-classic-leather', b: 'Reebok', d: '柔软皮面，EVA中底，经典复古跑鞋', p: 599 },
    { t: 'New Balance 990v6 美产', s: 'new-balance-990v6-usa', b: 'New Balance', d: '美国制造，FuelCell中底，总统跑鞋', p: 1699 },
    { t: 'Mizuno 美津浓 预言12 跑鞋', s: 'mizuno-wave-prophecy-12', b: 'Mizuno', d: 'Infinity Wave全掌波浪片，旗舰缓震', p: 1599 },
    { t: 'ASICS 亚瑟士 GEL-1130', s: 'asics-gel-1130', b: 'ASICS', d: '复古跑鞋，GEL缓震，银色科技感', p: 690 },
    { t: 'DESCENTE 迪桑特 滑雪服 男款', s: 'descente-ski-jacket-men', b: 'DESCENTE', d: 'HEAT NAVI蓄热，MOTION 3D剪裁', p: 3999, mp: 5999 },
  ]},

  // ── 家具 (17 more → 20 total) ──
  { catSlug: 'furniture', bg: 'D97706', products: [
    { t: '宜家 比利 书柜', s: 'ikea-billy-bookcase', b: '宜家', d: '经典书柜，可调式层板，多色可选', p: 399, mp: 599 },
    { t: '宜家 卡拉克斯 开放储物柜', s: 'ikea-kallax-shelf', b: '宜家', d: '4×4格开放式，可搭配收纳盒', p: 699 },
    { t: '顾家家居 真皮沙发 三人位', s: 'kuka-leather-sofa-3seat', b: '顾家家居', d: '头层牛皮，高回弹海绵，北欧简约', p: 5999, mp: 8999 },
    { t: '芝华仕 功能沙发 头等舱', s: 'cheers-recliner-sofa', b: '芝华仕', d: '电动多角度调节，USB充电，科技布', p: 2999, mp: 4999 },
    { t: '宜家 马尔姆 6屉柜', s: 'ikea-malm-6-drawer', b: '宜家', d: '6抽屉柜，光滑运行，可配镜子', p: 999, mp: 1299 },
    { t: '曲美 北欧鞋柜 翻斗', s: 'qumei-shoe-cabinet', b: '曲美', d: '超薄翻斗设计，大容量，玄关必备', p: 599, mp: 899 },
    { t: '西昊 人体工学椅 M57', s: 'sihoo-ergonomic-chair-m57', b: '西昊', d: '4D扶手，网面透气，腰靠可调', p: 999, mp: 1399 },
    { t: '永艺 电脑椅 Monte 人体工学', s: 'uy-office-chair-monte', b: '永艺', d: '双背联动，头枕可调，5级气杆', p: 799, mp: 1199 },
    { t: '保友 金豪E 人体工学椅', s: 'ergonor-e-gold-chair', b: '保友', d: '5D扶手，意大利Donati底盘，进口网布', p: 1999, mp: 2799 },
    { t: '网易严选 电动升降桌 120cm', s: 'yanxuan-standing-desk-120', b: '网易严选', d: '双电机驱动，记忆高度，稳定不晃', p: 1499, mp: 1999 },
    { t: '宜家 利蒙 / 阿迪斯 桌子', s: 'ikea-linnmon-adils-desk', b: '宜家', d: '简约办公桌，120cm，搭配桌腿', p: 199 },
    { t: '梦百合 零压床垫 0压厚垫', s: 'mlily-zero-pressure-mattress', b: '梦百合', d: '0压记忆棉，非温感，冬天不变硬', p: 2999, mp: 4999 },
    { t: '喜临门 乳胶弹簧床垫 云眠', s: 'sleemon-latex-spring-mattress', b: '喜临门', d: '泰国进口乳胶+独立弹簧，分区支撑', p: 2499, mp: 3999 },
    { t: '左右家私 实木餐桌 4人位', s: 'zuoyou-dining-table-4seat', b: '左右家私', d: '白蜡木实木，哑光漆面，北欧风格', p: 2299, mp: 3299 },
    { t: '红苹果 床头柜 简约', s: 'red-apple-nightstand', b: '红苹果', d: '两抽屉设计，哑光贴面，静音导轨', p: 399 },
    { t: '维诗 实木茶几 胡桃木', s: 'verse-walnut-coffee-table', b: '维诗', d: '北美黑胡桃木，榫卯工艺，简约', p: 1299, mp: 1999 },
    { t: '双虎 电脑桌 120cm 简约', s: 'sunhoo-computer-desk-120', b: '双虎', d: '加厚台面，钢架结构，简约书桌', p: 299, mp: 499 },
  ]},

  // ── 床上用品 (17 more → 20 total) ──
  { catSlug: 'bedding', bg: 'FCD34D', products: [
    { t: '梦洁 纯棉四件套 60支', s: 'mendale-cotton-bedding-60s', b: '梦洁', d: '60支精梳棉，亲肤柔软，活性印染', p: 499, mp: 699 },
    { t: '博洋 天丝四件套 100支', s: 'boyoung-tencel-bedding-100s', b: '博洋', d: '100支天丝，冰丝般顺滑，夏季凉感', p: 699, mp: 999 },
    { t: '南极人 法兰绒毛毯 200×230', s: 'nanjiren-flannel-blanket', b: '南极人', d: '加厚法兰绒，珊瑚绒面，冬季保暖', p: 69.9, mp: 99.9 },
    { t: '富安娜 蚕丝枕 桑蚕丝', s: 'fuanna-silk-pillow', b: '富安娜', d: '100%桑蚕丝填充，柔软透气，亲肤', p: 199 },
    { t: '宜家 VÄDRA 纤维枕', s: 'ikea-vadra-pillow', b: '宜家', d: '中等硬度，可水洗，适合各种睡姿', p: 49.9 },
    { t: '无印良品 水洗棉被套 双人', s: 'muji-washed-cotton-cover', b: 'MUJI', d: '新疆棉水洗工艺，柔软亲肤，日式素色', p: 299, mp: 399 },
    { t: '安睡宝 记忆棉枕 慢回弹', s: 'aisleep-memory-foam-pillow', b: '安睡宝', d: '太空记忆棉，蝶形曲线，护颈承托', p: 149 },
    { t: '康尔馨 五星级酒店枕 鹅绒', s: 'comfore-hotel-goose-pillow', b: '康尔馨', d: '95%白鹅绒填充，五星级酒店同款', p: 399 },
    { t: '南极人 电热毯 双人 180×150', s: 'nanjiren-electric-blanket', b: '南极人', d: '双温双控，过热保护，可水洗', p: 129, mp: 199 },
    { t: '彩阳 电热毯 双人双控', s: 'caiyang-electric-blanket', b: '彩阳', d: '碳纤维发热，9档调温，定时关闭', p: 169 },
    { t: '雅兰 床垫 护脊款 1.8m', s: 'airland-mattress-spine-1-8', b: '雅兰', d: '独立袋装弹簧，乳胶面层，护脊设计', p: 2299, mp: 3299 },
    { t: '慕思 乳胶床垫 V6 1.8m', s: 'derucci-latex-mattress-v6', b: '慕思', d: '泰国进口乳胶，3D透气面料，零压感', p: 3999, mp: 5999 },
    { t: '网易严选 鹅绒被 白鹅绒 95%', s: 'yanxuan-goose-down-quilt', b: '网易严选', d: '95%白鹅绒，800+蓬松度，轻暖奢华', p: 999, mp: 1499 },
    { t: '恒源祥 羊毛被 澳洲羊毛', s: 'hengyuanxiang-wool-quilt', b: '恒源祥', d: '100%澳洲羊毛，吸湿透气，四季通用', p: 599, mp: 899 },
    { t: '小米 8H乳胶弹簧床垫 青春版', s: 'xiaomi-8h-mattress-youth', b: '小米', d: '独立弹簧+乳胶，21cm厚度，高性价比', p: 1299, mp: 1799 },
    { t: '京东京造 纯棉四件套 A类', s: 'jd-made-cotton-bedding-a', b: '京东京造', d: 'A类婴幼儿标准，40支纯棉，简约素色', p: 199, mp: 299 },
    { t: '淘宝心选 天竺棉四件套', s: 'taobao-jersey-cotton-bedding', b: '淘宝心选', d: '针织天竺棉，T恤般柔软，日式条纹', p: 159, mp: 229 },
  ]},

  // ── 收纳 (17 more → 20 total) ──
  { catSlug: 'storage', bg: '6B7280', products: [
    { t: '宜家 斯库布 储物盒 6件套', s: 'ikea-skubb-storage-6set', b: '宜家', d: '衣柜收纳盒，无纺布材质，可折叠', p: 79.9 },
    { t: '百露 可折叠收纳箱 66L 3个', s: 'bailu-folding-box-66l-3', b: '百露', d: '加厚PP材质，折叠不占空间，带盖', p: 79.9 },
    { t: '纳川 桌面抽屉式收纳盒', s: 'nachuang-drawer-organizer', b: '纳川', d: '透明抽屉，桌面化妆品文具收纳', p: 39.9, mp: 69.9 },
    { t: '美丽雅 脚踏垃圾桶 12L', s: 'meliya-pedal-bin-12l', b: '美丽雅', d: '缓降静音，脚踏开盖，厨房客厅通用', p: 49.9 },
    { t: '茶花 密封米桶 15kg', s: 'chahua-rice-container-15kg', b: '茶花', d: '翻盖密封，防虫防潮，带量杯', p: 39.9 },
    { t: '太力 衣物防尘罩 10个', s: 'taili-garment-covers-10', b: '太力', d: 'PEVA透明防尘，挂式衣服罩，防潮', p: 19.9 },
    { t: '居家家 冰箱收纳盒 4个装', s: 'jujia-fridge-organizer-4', b: '居家家', d: '透明PET材质，可叠加，冰箱整理', p: 29.9 },
    { t: '百易特 内衣收纳盒 三件套', s: 'baiyite-underwear-box-3set', b: '百易特', d: '分格设计，内衣袜子收纳，可水洗', p: 29.9 },
    { t: '简趣 桌面收纳盒 多层', s: 'jianqu-desk-organizer', b: '简趣', d: '亚克力透明，多层旋转，化妆品收纳', p: 49.9 },
    { t: '溢彩年华 置物架 五层', s: 'yicai-storage-rack-5tier', b: '溢彩年华', d: '碳钢材质，免打孔，厨房浴室通用', p: 89.9, mp: 139.9 },
    { t: '心家宜 厨房置物架 不锈钢', s: 'xinjiayi-kitchen-rack-steel', b: '心家宜', d: '304不锈钢，壁挂式，调料架刀架', p: 69.9 },
    { t: '宜家 拉斯克 手推车', s: 'ikea-raskog-trolley', b: '宜家', d: '三层手推车，万向轮，移动收纳', p: 249 },
    { t: '安尔雅 旋转化妆品收纳盒', s: 'anerya-rotating-makeup-box', b: '安尔雅', d: '360度旋转，透明亚克力，多层分格', p: 39.9 },
    { t: '懒角落 调料架 旋转 双层', s: 'lazy-corner-spice-rack', b: '懒角落', d: '360度旋转，双层设计，厨房调料收纳', p: 39.9 },
    { t: '百家好世 简易鞋架 8层', s: 'baijia-shoe-rack-8tier', b: '百家好世', d: '不锈钢管，防尘布罩，门口玄关', p: 49.9 },
    { t: '蔻丝 落地衣帽架 实木', s: 'cose-coat-rack-wood', b: '蔻丝', d: '橡胶木实木，8钩设计，北欧简约', p: 89.9 },
    { t: '博采 A4文件收纳柜 5层', s: 'bocai-file-cabinet-5tier', b: '博采', d: '桌面文件柜，5层抽屉，办公室整理', p: 39.9 },
  ]},

  // ── 奶粉 (17 more → 20 total) ──
  { catSlug: 'milk-powder', bg: 'FB923C', products: [
    { t: 'a2 白金版 婴幼儿配方奶粉 3段 900g', s: 'a2-platinum-stage3-900g', b: 'a2', d: 'A2 β-酪蛋白，新西兰原装进口', p: 298, mp: 548 },
    { t: '皇家美素佳儿 3段 800g', s: 'friso-prestige-stage3-800g', b: '美素佳儿', d: '天然乳脂小分子，荷兰原装进口', p: 328, mp: 598 },
    { t: '合生元 派星 3段 900g', s: 'biostime-star-stage3-900g', b: '合生元', d: 'SN-2 PLUS+天然乳脂，法国原罐进口', p: 298, mp: 548 },
    { t: '君乐宝 恬适 3段 800g', s: 'junlebao-tianshi-stage3-800g', b: '君乐宝', d: '小分子蛋白，CPP促吸收，高性价比', p: 158, mp: 298 },
    { t: '伊利 金领冠 珍护 3段 900g', s: 'yili-gold-crown-stage3-900g', b: '伊利', d: '中国专利配方，α+β专利蛋白组合', p: 268, mp: 498 },
    { t: '贝因美 爱加 3段 800g', s: 'beingmate-love-stage3-800g', b: '贝因美', d: '乳铁蛋白+DHA，适合中国宝宝体质', p: 218, mp: 398 },
    { t: '雅培 菁挚 有机 2段 900g', s: 'abbott-eleva-organic-2-900g', b: '雅培', d: '欧盟有机认证，丹麦原罐进口', p: 338, mp: 618 },
    { t: '惠氏 启赋 蓝钻 3段 850g', s: 'wyeth-illuma-stage3-850g', b: '惠氏', d: 'O-P-O结构脂，乳源活性因子', p: 308, mp: 568 },
    { t: '达能 诺优能 3段 800g', s: 'danone-nutrilon-stage3-800g', b: '达能', d: '100%乳糖配方，荷兰进口奶源', p: 198, mp: 368 },
    { t: '可瑞康 金装 3段 900g', s: 'karicare-gold-stage3-900g', b: '可瑞康', d: '新西兰原产，DHA+益生元组合', p: 188, mp: 348 },
    { t: '明一 天籁牧羊 3段 800g', s: 'mingyi-goat-stage3-800g', b: '明一', d: '纯羊乳蛋白，小分子好吸收', p: 298, mp: 548 },
    { t: '宜品 蓓康僖 羊奶粉 3段 800g', s: 'yiping-goat-stage3-800g', b: '宜品', d: '西班牙进口羊奶源，A2蛋白', p: 318, mp: 588 },
    { t: '澳优 能力多 3段 900g', s: 'ausnutria-stage3-900g', b: '澳优', d: '荷兰原罐进口，乳铁蛋白+益生菌', p: 248, mp: 458 },
    { t: '蓝河 姆阿普 3段 800g', s: 'blue-river-maap-stage3-800g', b: '蓝河', d: '新西兰绵羊奶，天然A2蛋白', p: 358, mp: 658 },
    { t: '佳贝艾特 悦白 3段 800g', s: 'kabrita-gold-stage3-800g', b: '佳贝艾特', d: '荷兰进口羊奶粉，OPO+DHA', p: 388, mp: 718 },
    { t: '圣元 优博 3段 900g', s: 'synutra-stage3-900g', b: '圣元', d: '法国原罐进口，58种营养素', p: 198, mp: 368 },
    { t: '雅士利 瑞哺恩 3段 800g', s: 'yashili-stage3-800g', b: '雅士利', d: '新西兰原罐进口，DHA+ARA', p: 158, mp: 288 },
  ]},

  // ── 纸尿裤 (17 more → 20 total) ──
  { catSlug: 'diapers', bg: 'A855F7', products: [
    { t: '大王 光羽 纸尿裤 L52片', s: 'goon-premium-diaper-l52', b: '大王', d: '日本进口，柔软透气，轻薄干爽', p: 129, mp: 239 },
    { t: '尤妮佳 moony 皇家 纸尿裤 M64', s: 'moony-royal-diaper-m64', b: '尤妮佳', d: '有机棉表层，3D贴合，日本原装', p: 139, mp: 249 },
    { t: 'Babycare 皇室弱酸纸尿裤 L48', s: 'babycare-royal-diaper-l48', b: 'Babycare', d: '弱酸性表层，超柔亲肤，三重锁水', p: 119, mp: 219 },
    { t: '爹地宝贝 云柔 拉拉裤 XL40', s: 'daddy-baby-pull-up-xl40', b: '爹地宝贝', d: '云朵般柔软，360度弹力腰围', p: 79.9, mp: 149 },
    { t: '安儿乐 小轻芯 纸尿裤 L52', s: 'anerle-thin-diaper-l52', b: '安儿乐', d: '超薄1.5mm，10h干爽不断层', p: 89.9, mp: 169 },
    { t: '雀氏 铂金装 拉拉裤 XL36', s: 'chiaus-platinum-pull-up-xl36', b: '雀氏', d: '德国工艺，4D柔韧弹力，大环腰', p: 99.9, mp: 179 },
    { t: '碧芭宝贝 盛夏光年 纸尿裤 S72', s: 'bibababy-summer-diaper-s72', b: '碧芭宝贝', d: '夏季透气款，超薄凉感，全芯体', p: 99.9, mp: 179 },
    { t: '露安适 小光圈 纸尿裤 M56', s: 'luanshi-aperture-diaper-m56', b: '露安适', d: '医护级亲肤，0.1%荧光剂残留', p: 109, mp: 199 },
    { t: 'BEABA 碧芭 拉拉裤 L42', s: 'beaba-pull-up-pants-l42', b: 'BEABA', d: '法国品牌，盛夏系列，薄至1mm', p: 89.9, mp: 169 },
    { t: '丽贝乐 comfort 纸尿裤 L44', s: 'libero-comfort-diaper-l44', b: '丽贝乐', d: '瑞典品牌，全芯体干爽，V型剪裁', p: 109 },
    { t: '好奇 心钻装 拉拉裤 XXL32', s: 'huggies-diamond-pull-up-xxl32', b: '好奇', d: '丝柔质感，更大尺码，学步期专用', p: 109, mp: 199 },
    { t: '帮宝适 纯净帮 纸尿裤 NB76', s: 'pampers-pure-nb76', b: '帮宝适', d: '植物基材料，0添加香精，新生儿', p: 99.9, mp: 179 },
    { t: '大王 天使 纸尿裤 S82', s: 'goon-angel-diaper-s82', b: '大王', d: '天使系列，维E呵护，新生柔软', p: 109, mp: 199 },
    { t: 'Bambo Nature 自然纸尿裤 L40', s: 'bambo-nature-diaper-l40', b: 'Bambo Nature', d: '丹麦有机，北欧白天鹅认证，环保', p: 149 },
    { t: '嫚熙 婴儿湿巾 80抽×12包', s: 'emxee-baby-wipes-80x12', b: '嫚熙', d: 'EDI纯水+RO反渗透，加厚珍珠纹', p: 49.9 },
    { t: '全棉时代 婴儿棉柔巾 100抽×6', s: 'purcotton-baby-tissue-6pack', b: '全棉时代', d: '100%天然棉，干湿两用，宝宝面口手', p: 59.9 },
    { t: '子初 婴儿洗衣液 1.5L×2', s: 'zichu-baby-laundry-liquid', b: '子初', d: '植物酵素，温和不刺激，无荧光剂', p: 39.9 },
  ]},

  // ── 玩具 (16 more → 20 total) ──
  { catSlug: 'toys', bg: 'EAB308', products: [
    { t: '乐高 城市系列 警察局 60316', s: 'lego-city-police-station', b: 'LEGO', d: '668片零件，含4个人仔+警车+直升机', p: 499 },
    { t: '万代 高达 RG 牛高达', s: 'bandai-rg-nu-gundam', b: '万代', d: 'RG 1/144比例，精密可动，高还原度', p: 299 },
    { t: '变形金刚 SS系列 擎天柱', s: 'transformers-ss-optimus-prime', b: '孩之宝', d: 'Studio Series电影级，高度可变形', p: 299, mp: 499 },
    { t: '小马宝莉 友谊魔法城堡', s: 'mlp-friendship-castle', b: '孩之宝', d: '声光互动，含人偶配件，梦幻城堡', p: 199, mp: 299 },
    { t: '芭比 梦幻衣橱套装', s: 'barbie-dream-closet', b: 'Mattel', d: '含娃娃+30件衣服配饰，时尚换装', p: 299 },
    { t: '奥特曼 迪迦变身器 超古代光', s: 'ultraman-tiga-spark-lens', b: '万代', d: '声光变身器，经典迪迦造型，角色扮演', p: 149 },
    { t: '森贝儿家族 甜梦小屋', s: 'sylvanian-sweet-dream-house', b: '森贝儿', d: '精致小屋+家具套装，激发想象力', p: 299, mp: 499 },
    { t: '多美卡 合金小汽车 10辆套装', s: 'tomica-diecast-10pack', b: '多美卡', d: '日本TOMY正版，锌合金车身，收藏级', p: 199 },
    { t: '邦宝 积木 航天飞船 6402', s: 'banbao-space-shuttle-6402', b: '邦宝', d: '国产精品积木，630片，含宇航员', p: 149 },
    { t: '木玩世家 七巧板 磁力', s: 'muwanshijia-tangram-magnetic', b: '木玩世家', d: '磁力吸附，优质榉木，早教益智', p: 49.9 },
    { t: '火火兔 早教机 G6s', s: 'huohuotu-learning-machine-g6s', b: '火火兔', d: '智能语音，海量资源，防摔硅胶', p: 199, mp: 299 },
    { t: '小天才 儿童电话手表 Z8', s: 'xtc-phone-watch-z8', b: '小天才', d: '翻转双摄，九重安全定位，视频通话', p: 998, mp: 1598 },
    { t: 'Hape 厨房玩具套装 木质', s: 'hape-kitchen-play-set', b: 'Hape', d: '德国品牌，环保水性漆，角色扮演', p: 299, mp: 499 },
    { t: 'Playmobil 摩比世界 海盗船', s: 'playmobil-pirate-ship', b: 'Playmobil', d: '德国品牌，可浮水，含海盗人偶', p: 399 },
    { t: '磁力片 百变提拉积木 120片', s: 'magnetic-tiles-120pcs', b: '贝思迪', d: '强磁力片，多形状组合，STEM教育', p: 129, mp: 199 },
    { t: '泡泡机 全自动 电动', s: 'auto-bubble-machine', b: '乐缔', d: '全自动吹泡泡，彩灯效果，户外玩具', p: 29.9, mp: 49.9 },
  ]},
];
